import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const read = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");
const json = (path: string) => JSON.parse(read(path));

describe("Lovable build isolation", () => {
  it("keeps the canonical npm install and Vite build free of Lovable packages", () => {
    const rootPackage = json("package.json");
    const rootDependencies = {
      ...rootPackage.dependencies,
      ...rootPackage.devDependencies,
      ...rootPackage.optionalDependencies,
    };
    expect(Object.keys(rootDependencies).filter((name) => name.includes("lovable"))).toEqual([]);

    const vite = read("vite.config.ts");
    expect(vite).not.toMatch(/lovable-tagger|@lovable\.dev\/mcp-js/);
    expect(vite).not.toContain("mcpPlugin");
    expect(vite).not.toContain("componentTagger");

    const dockerfile = read("Dockerfile");
    expect(dockerfile).not.toContain("VITE_SUPABASE_PROJECT_ID");
    expect(dockerfile).not.toContain("lovable");
    expect(existsSync(resolve(process.cwd(), ".env"))).toBe(false);
  });

  it("builds and exercises the pinned portable Nginx container in CI", () => {
    const dockerfile = read("Dockerfile");
    const nginx = read("deploy/nginx.conf");
    const workflow = read(".github/workflows/ci.yml");
    const builderImage =
      "node:22.22.0-alpine3.23@sha256:e4bf2a82ad0a4037d28035ae71529873c069b13eb0455466ae0bc13363826e34";
    const runtimeImage =
      "nginx:1.30.4-alpine@sha256:97d490c12ba55b4946b01546d1c3ed324e8d41ab1c9fcb2a616aa470620e5b46";

    expect(dockerfile).toContain(`FROM ${builderImage} AS build`);
    expect(dockerfile).toContain(`FROM ${runtimeImage} AS runtime`);
    expect(dockerfile).toContain("npm install --global npm@11.9.0");
    expect(dockerfile).toContain(
      "CMD curl -fsS -o /dev/null http://127.0.0.1:8080/healthz || exit 1",
    );

    const assetsBlock = nginx.match(/location \^~ \/assets\/ \{([\s\S]*?)\n\s{2}\}/)?.[0] ?? "";
    expect(assetsBlock).toContain('Cache-Control "public, max-age=31536000, immutable"');
    expect(assetsBlock).toContain('X-Content-Type-Options "nosniff"');
    expect(assetsBlock).toContain('Referrer-Policy "strict-origin-when-cross-origin"');
    expect(nginx.replace(assetsBlock, "")).not.toContain("immutable");
    expect(nginx).toContain('Cache-Control "no-store"');
    expect(nginx).toContain("try_files $uri $uri/ /index.html");

    expect(workflow).toContain("docker build --pull");
    expect(workflow).toContain("docker run --detach");
    expect(workflow).toContain("X-Content-Type-Options: nosniff");
    expect(workflow).toContain("Referrer-Policy: strict-origin-when-cross-origin");
    expect(workflow).toContain("Cache-Control: public, max-age=31536000, immutable");
    expect(workflow).toContain("--publish 127.0.0.1:18080:8080");
    expect(workflow).toContain(".State.Health.Status");
    expect(workflow).toContain("http://127.0.0.1:18080/healthz");
    expect(workflow).toContain("for route in login conectar-mcp calendario");
    expect(workflow).toContain('cmp --silent "$index_file" "$route_file"');
    expect(workflow).toContain("if: always()");
    expect(workflow).toContain("docker rm --force aceleriq-os-ci");
  });

  it("pins legacy MCP compatibility outside the root build", () => {
    const compatPackage = json("integrations/lovable-mcp-compat/package.json");
    const manifest = json(".lovable/mcp/manifest.json");
    const generated = read("supabase/functions/mcp/index.ts");
    const compatVite = read("integrations/lovable-mcp-compat/vite.config.ts");
    const sdkVersion = compatPackage.devDependencies["@lovable.dev/mcp-js"];

    expect(sdkVersion).toBe("0.23.0");
    expect(manifest.sdk_version).toBe(sdkVersion);
    expect(manifest.path).toBe("/functions/v1/mcp");
    expect(generated).toContain(`npm:@lovable.dev/mcp-js@${sdkVersion}`);
    expect(generated).toMatch(/^\/\/ AUTO-GENERATED by @lovable\.dev\/mcp-js/);
    expect(compatVite).toContain("compatibilityProjectRef");
  });

  it("installs and validates the opt-in compatibility package in CI", () => {
    const workflow = read(".github/workflows/supabase-db-tests.yml");

    expect(workflow).toContain("integrations/lovable-mcp-compat/package-lock.json");
    expect(workflow).toContain("npm ci --prefix integrations/lovable-mcp-compat");
    expect(workflow).toContain("npm --prefix integrations/lovable-mcp-compat run verify");
    expect(workflow).toContain("npm --prefix integrations/lovable-mcp-compat run generate");
    expect(workflow).toContain("git diff --exit-code --");
    expect(workflow).toContain(".lovable/mcp/manifest.json");
    expect(workflow).toContain("supabase/functions/mcp/index.ts");
    expect(workflow).not.toContain("npx lovable-mcp-extract-manifest");
  });
});
