/**
 * Rótulos em português da base UI UX Pro Max (frente UXM, 30/09/2026). Texto
 * NOSSO: a base é só em inglês; aqui ficam os nomes que a tela mostra e o
 * "como corrigir" das regras de UX da web. Os ids (número do produto, id do
 * estilo, id do padrão, número da regra) são os da base 2.15.0; o teste
 * src/test/uix-base-de-design.test.ts cobra a cobertura (todo produto, todo
 * estilo ativo, todo padrão e toda regra Web ou All têm texto aqui).
 *
 * Puro, sem import. Sem travessão.
 */

/** Tipo de produto (pelo "No" de products.csv) em português. */
export const ROTULO_DO_PRODUTO: Record<string, string> = {
  "1": "SaaS (geral)",
  "2": "Micro SaaS",
  "3": "Loja virtual",
  "4": "Loja virtual de luxo",
  "5": "Serviço B2B",
  "6": "Painel financeiro",
  "7": "Painel de análise de dados",
  "8": "App de saúde",
  "9": "App educacional",
  "10": "Agência criativa",
  "11": "Portfólio pessoal",
  "12": "Jogos",
  "13": "Governo e serviço público",
  "14": "Fintech e cripto",
  "15": "Rede social",
  "16": "Ferramenta de produtividade",
  "17": "Design system e biblioteca de componentes",
  "18": "Plataforma de IA e chatbot",
  "19": "Plataforma NFT e Web3",
  "20": "Plataforma para criadores de conteúdo",
  "21": "Trabalho remoto e colaboração",
  "22": "App de saúde mental",
  "23": "App para pets",
  "24": "Casa inteligente e IoT",
  "25": "Carro elétrico e recarga",
  "26": "Clube de assinatura",
  "27": "Plataforma de podcast",
  "28": "App de relacionamento",
  "29": "Microcertificações e selos",
  "30": "Base de conhecimento e documentação",
  "31": "Serviços de bairro",
  "32": "Beleza, spa e bem-estar",
  "33": "Marca de luxo e premium",
  "34": "Restaurante e alimentação",
  "35": "Academia e fitness",
  "36": "Imobiliária",
  "37": "Agência de viagens e turismo",
  "38": "Hotel e hospitalidade",
  "39": "Casamentos e eventos",
  "40": "Serviços jurídicos",
  "41": "Seguros",
  "42": "Banco e finanças tradicionais",
  "43": "Curso online",
  "44": "ONG e causa social",
  "45": "Streaming de música",
  "46": "Streaming de vídeo",
  "47": "Vagas e recrutamento",
  "48": "Marketplace entre pessoas",
  "49": "Logística e entregas",
  "50": "Agronegócio e tecnologia no campo",
  "51": "Construção e arquitetura",
  "52": "Automotivo e concessionária",
  "53": "Estúdio de fotografia",
  "54": "Coworking",
  "55": "Serviços em casa (encanador, eletricista)",
  "56": "Creche e cuidado infantil",
  "57": "Cuidado de idosos",
  "58": "Clínica médica",
  "59": "Farmácia",
  "60": "Clínica odontológica",
  "61": "Clínica veterinária",
  "62": "Floricultura",
  "63": "Padaria e café",
  "64": "Cervejaria e vinícola",
  "65": "Companhia aérea",
  "66": "Notícias e mídia",
  "67": "Revista e blog",
  "68": "Plataforma de freelancers",
  "69": "Agência de marketing",
  "70": "Gestão de eventos",
  "71": "Comunidade e assinatura de membros",
  "72": "Newsletter",
  "73": "Produtos digitais",
  "74": "Igreja e organização religiosa",
  "75": "Clube e time esportivo",
  "76": "Museu e galeria",
  "77": "Teatro e cinema",
  "78": "App de idiomas",
  "79": "Escola de programação",
  "80": "Segurança digital",
  "81": "Ferramenta para desenvolvedores",
  "82": "Biotecnologia e ciências da vida",
  "83": "Tecnologia espacial",
  "84": "Arquitetura e interiores",
  "85": "Computação quântica",
  "86": "Longevidade e biohacking",
  "87": "Frota de drones",
  "88": "Arte generativa",
  "89": "Computação espacial",
  "90": "Energia limpa e clima",
  "91": "Finanças pessoais",
  "92": "App de mensagens",
  "93": "App de notas e escrita",
  "94": "Rastreador de hábitos",
  "95": "Delivery de comida",
  "96": "Transporte por aplicativo",
  "97": "Receitas e culinária",
  "98": "Meditação e atenção plena",
  "99": "Previsão do tempo",
  "100": "Diário pessoal",
  "101": "CRM e gestão de clientes",
  "102": "Controle de estoque",
  "103": "Estudos e flashcards",
  "104": "Agendamento e reservas",
  "105": "Faturamento e cobrança",
  "106": "Lista de compras",
  "107": "Timer e pomodoro",
  "108": "Maternidade e bebê",
  "109": "Scanner e documentos",
  "110": "Agenda e calendário",
  "111": "Gerenciador de senhas",
  "112": "Divisão de contas",
  "113": "Gravador de voz",
  "114": "Favoritos e ler depois",
  "115": "Tradutor",
  "116": "Calculadora e conversor",
  "117": "Despertador e relógio mundial",
  "118": "Arquivos e transferência",
  "119": "Cliente de e-mail",
  "120": "Jogo de quebra-cabeça",
  "121": "Jogo de perguntas",
  "122": "Jogo de cartas e tabuleiro",
  "123": "Jogo de clique",
  "124": "Jogo de palavras",
  "125": "Jogo retrô e fliperama",
  "126": "Editor de fotos",
  "127": "Editor de vídeos curtos",
  "128": "Desenho e rascunho",
  "129": "Produção musical",
  "130": "Memes e figurinhas",
  "131": "Fotos e avatares com IA",
  "132": "Página de links na bio",
  "133": "Guarda-roupa e looks",
  "134": "Cuidado de plantas",
  "135": "Leitura e livros",
  "136": "App para casais",
  "137": "Agenda da família e tarefas",
  "138": "Registro de humor",
  "139": "Presentes e lista de desejos",
  "140": "Corrida e ciclismo",
  "141": "Yoga e alongamento",
  "142": "Sono",
  "143": "Nutrição e calorias",
  "144": "Ciclo menstrual",
  "145": "Lembrete de remédios",
  "146": "Hidratação",
  "147": "Jejum intermitente",
  "148": "Comunidade anônima",
  "149": "Eventos locais",
  "150": "Estudo em grupo e coworking virtual",
  "151": "Desafios de programação",
  "152": "Aprendizado infantil",
  "153": "Aulas de instrumento musical",
  "154": "Estacionamento",
  "155": "Transporte público",
  "156": "Roteiro de viagem de carro",
  "157": "VPN e privacidade",
  "158": "Emergência e segurança",
  "159": "Papéis de parede e temas",
  "160": "Ruído branco e sons ambientes",
  "161": "Decoração e design de interiores",
  "162": "Revista científica",
  "163": "Portal de API para desenvolvedores",
  "164": "Fórum de discussão",
  "165": "Guia e diretório",
  "166": "Página de status e incidentes",
  "167": "Wiki e enciclopédia",
  "168": "Leilão",
  "169": "Novidades e versões",
  "170": "Ciência cidadã",
  "171": "Classificados",
  "172": "Congresso e simpósio",
  "173": "Financiamento coletivo",
  "174": "Totem e sinalização digital",
  "175": "Assinatura eletrônica",
  "176": "Configuração de funcionalidades",
  "177": "Portal de serviços ao cidadão",
  "178": "Editais e financiamento",
  "179": "Plataforma de ensino (LMS)",
  "180": "Construtor no-code",
  "181": "Projeto de código aberto",
  "182": "Portal do paciente",
  "183": "Patentes e propriedade intelectual",
  "184": "Comunidade de perguntas e respostas",
  "185": "Laboratório e departamento universitário",
  "186": "Criador de currículo",
  "187": "Plataforma de avaliações",
  "188": "Painel de automação",
  "189": "Formulários e pesquisas",
  "190": "Telemedicina",
  "191": "Depoimentos e prova social",
  "192": "Ingressos e bilheteria",
};

export type EstiloEmPortugues = { rotulo: string; resumo: string; evitar: string };

/** Os 50 estilos ativos (pelo Style ID): nome, o que é e quando evitar. */
export const ESTILO_EM_PORTUGUES: Record<string, EstiloEmPortugues> = {
  "minimalism-and-swiss-style": { rotulo: "Minimalismo suíço", resumo: "Muito espaço, grade rígida, sans e alto contraste; sóbrio e funcional.", evitar: "marcas lúdicas, entretenimento e portfólio artístico" },
  neumorphism: { rotulo: "Neumorfismo", resumo: "Relevo suave, cantos arredondados e pouca cor; calmo.", evitar: "muito dado na tela e quem precisa de alto contraste" },
  glassmorphism: { rotulo: "Vidro fosco", resumo: "Camadas translúcidas e desfocadas sobre fundo vivo; moderno e premium.", evitar: "fundo de baixo contraste e acessibilidade crítica" },
  brutalism: { rotulo: "Brutalismo", resumo: "Cru, contraste máximo, bordas à mostra e tipografia padrão; ousado.", evitar: "empresas conservadoras e atendimento ao público" },
  "3d-and-hyperrealism": { rotulo: "3D e hiper-realismo", resumo: "Profundidade, texturas reais e objetos 3D; imersivo.", evitar: "celular simples, formulários e acessibilidade crítica" },
  "vibrant-and-block-based": { rotulo: "Vibrante em blocos", resumo: "Cores fortes, blocos geométricos e energia; jovem.", evitar: "finanças, saúde, governo e público idoso" },
  "dark-mode-oled": { rotulo: "Escuro profundo", resumo: "Fundo preto com contraste alto; noturno e tecnológico.", evitar: "conteúdo para imprimir e uso sob sol forte" },
  "accessible-and-ethical": { rotulo: "Acessível e ético", resumo: "Alto contraste, letra grande, teclado e leitor de tela; feito para todos.", evitar: "nenhum caso: acessibilidade vale sempre" },
  claymorphism: { rotulo: "Massinha 3D", resumo: "3D macio, bordas grossas e sombras duplas; lúdico.", evitar: "serviços formais, jurídico, finanças e saúde séria" },
  "aurora-ui": { rotulo: "Aurora", resumo: "Degradês luminosos em malha, como aurora boreal; atmosférico.", evitar: "painéis densos e conteúdo longo" },
  "retro-futurism": { rotulo: "Retrofuturismo", resumo: "Neon, anos 80 e linhas de TV antiga; nostálgico.", evitar: "setores conservadores, jurídico e finanças" },
  "flat-design": { rotulo: "Flat", resumo: "Cores chapadas, sem sombra e formas simples; direto e rápido.", evitar: "luxo, experiência imersiva e muito detalhe" },
  skeuomorphism: { rotulo: "Esqueumorfismo", resumo: "Texturas e objetos do mundo real na tela; tátil.", evitar: "empresas modernas e acessibilidade crítica" },
  "liquid-glass": { rotulo: "Vidro líquido", resumo: "Material translúcido que refrata a luz, no jeito da Apple; fluido.", evitar: "áreas de leitura densa sem alternativa acessível" },
  "motion-driven": { rotulo: "Movido a movimento", resumo: "Animações, transições e efeitos na rolagem; dinâmico.", evitar: "painéis de dados, quem é sensível a movimento e aparelho fraco" },
  "micro-interactions": { rotulo: "Microinterações", resumo: "Pequenas animações que respondem ao toque e ao clique; vivo.", evitar: "desempenho crítico sem alternativa acessível" },
  "inclusive-design": { rotulo: "Design inclusivo", resumo: "Contraste, daltonismo, voz e leitor de tela pensados desde o começo.", evitar: "nenhum caso: inclusão vale sempre" },
  "zero-interface": { rotulo: "Interface invisível", resumo: "Quase sem tela: voz, gesto e previsão.", evitar: "fluxos complexos e muito preenchimento de dados" },
  "soft-ui-evolution": { rotulo: "Relevo suave moderno", resumo: "Relevo discreto com contraste melhor e acessível; profissional.", evitar: "minimalismo extremo" },
  "data-dense-dashboard": { rotulo: "Painel denso de dados", resumo: "Muitos gráficos e tabelas em pouco espaço; analítico.", evitar: "site de marketing e números para o público final" },
  neubrutalism: { rotulo: "Neobrutalismo", resumo: "Contorno preto grosso, sombra dura e cores primárias; divertido.", evitar: "luxo, finanças e saúde" },
  "bento-box-grid": { rotulo: "Grade bento", resumo: "Blocos de tamanhos diferentes, no jeito da Apple; organizado.", evitar: "tabelas densas e texto longo" },
  "y2k-aesthetic": { rotulo: "Estética anos 2000", resumo: "Cromado, rosa neon e brilho dos anos 2000; nostálgico.", evitar: "B2B, saúde, finanças e público idoso" },
  "cyberpunk-ui": { rotulo: "Cyberpunk", resumo: "Neon sobre escuro, falha de sinal e cara de terminal.", evitar: "empresas tradicionais, saúde e famílias" },
  "organic-biophilic": { rotulo: "Orgânico e natural", resumo: "Formas naturais, verdes e terrosos; sustentável.", evitar: "tecnologia pura, jogos e indústria" },
  "ai-native-ui": { rotulo: "Nativo de IA", resumo: "Conversa, assistente e pouca moldura; focado no diálogo.", evitar: "formulários tradicionais e painéis densos" },
  "memphis-design": { rotulo: "Memphis", resumo: "Formas geométricas, padrões e cores dos anos 80; irreverente.", evitar: "finanças, saúde, jurídico e público idoso" },
  "dimensional-layering": { rotulo: "Camadas em profundidade", resumo: "Sobreposição, sombra e elevação que organizam a hierarquia.", evitar: "blog simples e aparelho fraco" },
  "exaggerated-minimalism": { rotulo: "Minimalismo exagerado", resumo: "Tipografia gigante, contraste alto e muito vazio; marcante.", evitar: "catálogo de loja, formulários e painéis de dados" },
  "kinetic-typography": { rotulo: "Tipografia cinética", resumo: "Texto que se move e se monta com a rolagem; impactante.", evitar: "texto longo, formulários e acessibilidade crítica" },
  "parallax-storytelling": { rotulo: "História em parallax", resumo: "Narrativa contada na rolagem, em camadas; cinematográfico.", evitar: "loja, painéis e site que depende de SEO e acessibilidade" },
  "hud-sci-fi-fui": { rotulo: "Painel de ficção científica", resumo: "Linhas técnicas, dados e neon como painel de nave.", evitar: "empresas comuns e leitura longa" },
  "pixel-art": { rotulo: "Pixel art", resumo: "8 e 16 bits, blocos e nostalgia de videogame.", evitar: "empresas sérias e fotografia em alta" },
  "spatial-ui-visionos": { rotulo: "Interface espacial", resumo: "Vidro, profundidade e gestos, no jeito do Vision Pro.", evitar: "documentos longos e quem precisa de alto contraste" },
  "e-ink-paper": { rotulo: "Papel e tinta eletrônica", resumo: "Fosco, textura de papel e leitura calma.", evitar: "jogos, vídeo e marketing de alta energia" },
  "gen-z-chaos-maximalism": { rotulo: "Maximalismo da geração Z", resumo: "Colagem, adesivos e excesso de propósito; barulhento.", evitar: "empresas, governo, saúde e bancos" },
  "biomimetic-organic-2-0": { rotulo: "Biomimético", resumo: "Formas vivas e generativas inspiradas na natureza; científico.", evitar: "SaaS comum e contabilidade" },
  "anti-polish-raw-aesthetic": { rotulo: "Cru e sem polimento", resumo: "Feito à mão, colagem e imperfeição autêntica.", evitar: "empresas, fintech, saúde e governo" },
  "tactile-digital-deformable-ui": { rotulo: "Tátil e deformável", resumo: "Botões de gelatina, massinha e resposta física ao toque.", evitar: "software corporativo e painéis de dados" },
  "nature-distilled": { rotulo: "Natureza destilada", resumo: "Terrosos suaves, madeira, argila e calor artesanal.", evitar: "startup de tecnologia, jogos e vida noturna" },
  "interactive-cursor-design": { rotulo: "Cursor interativo", resumo: "O cursor vira ferramenta e responde ao passar.", evitar: "celular (não tem cursor) e formulários" },
  "voice-first-multimodal": { rotulo: "Voz em primeiro lugar", resumo: "Conversa por voz com apoio visual; mãos livres.", evitar: "conteúdo muito visual e formulários complexos" },
  "3d-product-preview": { rotulo: "Produto em 3D", resumo: "Produto que gira, aproxima e se configura na tela.", evitar: "blog, painéis e internet lenta" },
  "editorial-grid-magazine": { rotulo: "Grade de revista", resumo: "Layout de revista, colunas, citações e letra capitular.", evitar: "painéis, apps e catálogo de loja" },
  "vintage-analog-retro-film": { rotulo: "Filme analógico", resumo: "Grão, polaroide e cores desbotadas; nostálgico e quente.", evitar: "tecnologia moderna, SaaS e saúde" },
  bauhaus: { rotulo: "Bauhaus", resumo: "Geometria, cores primárias e sombra dura; construtivo.", evitar: "painéis corporativos e acessibilidade crítica" },
  "material-you-md3-mobile": { rotulo: "Material 3", resumo: "O padrão do Android: cor tonal, movimento de mola e peças adaptáveis.", evitar: "marcas brutalistas e editoriais em preto e branco" },
  "fluent-2": { rotulo: "Fluent 2", resumo: "O padrão da Microsoft: calmo, arredondado e corporativo.", evitar: "produto que não deve parecer Microsoft" },
  "shopify-polaris": { rotulo: "Shopify Polaris", resumo: "O padrão do painel da Shopify para lojistas.", evitar: "site de marketing fora da Shopify" },
  "spectrum-design-system": { rotulo: "Adobe Spectrum", resumo: "O padrão da Adobe para ferramentas criativas profissionais.", evitar: "marca de consumo simples" },
};

/** Os 34 padrões de landing (pelo Pattern ID). */
export const ROTULO_DO_PADRAO: Record<string, string> = {
  "hero-features-cta": "Hero, recursos e CTA",
  "hero-testimonials-cta": "Hero, depoimentos e CTA",
  "product-demo-features": "Demo do produto e recursos",
  "minimal-single-column": "Coluna única minimalista",
  "funnel-3-step-conversion": "Funil de 3 passos",
  "comparison-table-cta": "Tabela comparativa e CTA",
  "lead-magnet-form": "Isca digital e formulário",
  "pricing-page-cta": "Página de preços e CTA",
  "video-first-hero": "Vídeo primeiro",
  "scroll-triggered-storytelling": "História na rolagem",
  "ai-personalization-landing": "Página personalizada por IA",
  "waitlist-coming-soon": "Lista de espera",
  "comparison-table-focus": "Foco no comparativo",
  "pricing-focused-landing": "Foco em preços",
  "app-store-style-landing": "Jeito de loja de apps",
  "faq-documentation-landing": "Perguntas e documentação",
  "immersive-interactive-experience": "Experiência imersiva",
  "event-conference-landing": "Evento e congresso",
  "product-review-ratings-focused": "Foco em avaliações",
  "community-forum-landing": "Comunidade e fórum",
  "before-after-transformation": "Antes e depois",
  "marketplace-directory": "Marketplace e diretório",
  "newsletter-content-first": "Newsletter e conteúdo",
  "webinar-registration": "Inscrição em webinar",
  "enterprise-gateway": "Portal corporativo",
  "portfolio-grid": "Grade de portfólio",
  "horizontal-scroll-journey": "Jornada em rolagem horizontal",
  "bento-grid-showcase": "Vitrine em bento",
  "interactive-3d-configurator": "Configurador 3D",
  "ai-driven-dynamic-landing": "Página dinâmica com IA",
  "feature-rich-showcase": "Vitrine de recursos",
  "hero-centric-design": "Hero dominante",
  "trust-authority-conversion": "Autoridade, confiança e conversão",
  "real-time-operations-landing": "Operação em tempo real",
};

export type SeveridadeDaRegra = "critica" | "alta" | "media" | "baixa";

/** Severidade da base (Critical, High, Medium, Low) em português. */
export const SEVERIDADE_DA_BASE: Record<string, SeveridadeDaRegra> = { Critical: "critica", High: "alta", Medium: "media", Low: "baixa" };
export const ROTULO_DA_SEVERIDADE: Record<SeveridadeDaRegra, string> = { critica: "Crítica", alta: "Alta", media: "Média", baixa: "Baixa" };
export const ORDEM_DA_SEVERIDADE: SeveridadeDaRegra[] = ["critica", "alta", "media", "baixa"];

export type RegraEmPortugues = { titulo: string; corrigir: string };

/** As 109 regras de UX da web (plataforma Web ou All), pelo "No" de ux-guidelines.csv. */
export const REGRA_DE_UX_EM_PORTUGUES: Record<string, RegraEmPortugues> = {
  "1": { titulo: "Rolagem suave nas âncoras", corrigir: "Ponha scroll-behavior: smooth no html e desligue com prefers-reduced-motion." },
  "2": { titulo: "Menu fixo sem cobrir o conteúdo", corrigir: "Reserve no topo a altura do menu fixo (padding ou scroll-padding-top) para ele não esconder o começo da seção." },
  "3": { titulo: "Item ativo do menu", corrigir: "Destaque o item da página ou seção atual com cor e sublinhado e marque aria-current." },
  "5": { titulo: "Endereço que acompanha o estado", corrigir: "Atualize o endereço (âncora ou parâmetro) quando a pessoa troca de aba ou filtro, para dar para compartilhar." },
  "6": { titulo: "Trilha de navegação", corrigir: "Use a trilha (Início, Categoria, Página) só quando o site tem 3 ou mais níveis." },
  "7": { titulo: "Excesso de animação", corrigir: "Anime só 1 ou 2 elementos principais por tela; o resto fica parado." },
  "8": { titulo: "Duração das animações", corrigir: "Use os tokens de movimento da casa (src/lib/movimento.ts) e confira que a resposta ao clique continua imediata." },
  "9": { titulo: "Movimento reduzido", corrigir: "Respeite @media (prefers-reduced-motion: reduce): pare animação, parallax e rolagem presa." },
  "10": { titulo: "Estado de carregamento", corrigir: "Mostre esqueleto ou indicador enquanto algo carrega; nunca deixe a tela parada sem resposta." },
  "11": { titulo: "Nada importante só no passar do mouse", corrigir: "Toda ação que aparece ao passar o mouse precisa funcionar com clique e com toque." },
  "12": { titulo: "Animação sem fim", corrigir: "Use animação contínua só em indicador de carregamento; enfeite não gira sem parar." },
  "13": { titulo: "Animar só transform e opacidade", corrigir: "Anime transform e opacity; nunca width, height, top ou left." },
  "14": { titulo: "Curva de aceleração", corrigir: "Desacelere ao entrar, acelere ao sair e use linear só em progresso constante." },
  "15": { titulo: "Camadas (z-index)", corrigir: "Defina uma escala curta de z-index (10, 20, 30, 50) e evite números enormes soltos." },
  "16": { titulo: "Conteúdo cortado", corrigir: "Não aplique overflow-hidden no escuro: confira que nada importante some cortado." },
  "17": { titulo: "Elementos fixos", corrigir: "Considere a altura dos elementos fixos e as áreas seguras do celular; nada fixo por cima de outro." },
  "18": { titulo: "Contexto de empilhamento", corrigir: "Lembre que transform, opacity e position criam contexto novo: o z-index não atravessa." },
  "19": { titulo: "Conteúdo que pula ao carregar", corrigir: "Reserve o espaço de imagem, selo e mensagem antes de chegarem (largura e altura, altura mínima)." },
  "20": { titulo: "Altura de tela no celular", corrigir: "Troque 100vh por min-h-screen com dvh por cima em tela cheia no celular." },
  "21": { titulo: "Largura de leitura", corrigir: "Limite o texto corrido a 65 ou 75 caracteres por linha (max-w-prose)." },
  "28": { titulo: "Foco visível", corrigir: "Mantenha um anel de foco (:focus-visible) em todo link, botão e campo; nunca tire o outline sem pôr outro." },
  "29": { titulo: "Resposta ao passar o mouse", corrigir: "Dê cursor de mão e uma mudança sutil de cor em tudo que é clicável." },
  "30": { titulo: "Estado pressionado", corrigir: "Mostre resposta imediata ao clicar ou tocar (leve escala ou cor)." },
  "31": { titulo: "Estado desabilitado", corrigir: "Deixe o desabilitado claramente diferente (opacidade menor e cursor de proibido)." },
  "32": { titulo: "Botão durante o envio", corrigir: "Desabilite o botão e mostre carregando enquanto envia, para não enviar duas vezes." },
  "33": { titulo: "Mensagem de erro", corrigir: "Mostre o erro claro perto do campo ou da ação que falhou; nunca falhe em silêncio." },
  "34": { titulo: "Confirmação de sucesso", corrigir: "Confirme a ação feita com mensagem curta ou sinal visual." },
  "35": { titulo: "Confirmar antes de apagar", corrigir: "Peça confirmação antes de qualquer ação que não dá para desfazer." },
  "36": { titulo: "Contraste de cor", corrigir: "Texto normal com pelo menos 4,5:1 sobre o fundo (3:1 no texto grande); use as cores da marca que passam." },
  "37": { titulo: "Informação só por cor", corrigir: "Junte ícone ou texto à cor (erro em vermelho com ícone e frase)." },
  "38": { titulo: "Texto alternativo", corrigir: "Toda imagem com conteúdo precisa de alt descritivo; a decorativa fica com alt vazio." },
  "39": { titulo: "Ordem dos títulos", corrigir: "Use h1, h2 e h3 em sequência, sem pular nível e sem título só para dar estilo." },
  "40": { titulo: "Nome acessível", corrigir: "Botão só com ícone precisa de aria-label." },
  "41": { titulo: "Navegação por teclado", corrigir: "A ordem do Tab segue a ordem visual e toda ação funciona sem mouse." },
  "42": { titulo: "HTML semântico", corrigir: "Use main, nav, header, footer e section em vez de div para tudo." },
  "43": { titulo: "Campo com rótulo", corrigir: "Todo campo precisa de label ligado (for e id) ou em volta; placeholder não é rótulo." },
  "44": { titulo: "Erro anunciado", corrigir: "Use role=\"alert\" ou aria-live na mensagem de erro para o leitor de tela anunciar." },
  "45": { titulo: "Pular para o conteúdo", corrigir: "Ponha no começo um link \"Pular para o conteúdo\" que leva ao main." },
  "46": { titulo: "Imagem otimizada", corrigir: "Sirva a imagem no tamanho certo e em formato leve (WebP ou AVIF) com srcset." },
  "47": { titulo: "Imagem sob demanda", corrigir: "Imagens abaixo da dobra com loading=\"lazy\"; a do hero carrega na hora." },
  "48": { titulo: "Código dividido", corrigir: "Separe o código por página ou recurso com import dinâmico." },
  "49": { titulo: "Cache", corrigir: "Configure cabeçalhos de cache para os arquivos com hash." },
  "50": { titulo: "Carregamento da fonte", corrigir: "Carregue a fonte com display=swap (ou optional) para o texto aparecer na hora." },
  "51": { titulo: "Script de terceiro", corrigir: "Carregue scripts de terceiros com async ou defer; rastreio só depois do consentimento." },
  "52": { titulo: "Tamanho do pacote", corrigir: "Acompanhe o tamanho do JavaScript e não traga biblioteca nova sem necessidade." },
  "53": { titulo: "Bloqueio da primeira pintura", corrigir: "Deixe o CSS crítico curto e adie o que não é da primeira dobra." },
  "54": { titulo: "Rótulo visível", corrigir: "Mostre o rótulo acima ou ao lado do campo; o placeholder some quando a pessoa digita." },
  "55": { titulo: "Erro junto do campo", corrigir: "Mostre o erro embaixo do campo e ligue os dois com aria-describedby." },
  "56": { titulo: "Validação ao sair do campo", corrigir: "Valide ao sair do campo, não só no envio." },
  "57": { titulo: "Tipo do campo", corrigir: "Use type=\"email\", \"tel\" e \"url\" nos campos certos (o celular abre o teclado certo)." },
  "58": { titulo: "Preenchimento automático", corrigir: "Use autocomplete (name, email, tel) para o navegador preencher." },
  "59": { titulo: "Campo obrigatório", corrigir: "Marque os obrigatórios com asterisco ou \"(obrigatório)\"." },
  "60": { titulo: "Ver a senha", corrigir: "Dê um botão para mostrar e esconder a senha." },
  "61": { titulo: "Retorno do envio", corrigir: "Mostre carregando e depois sucesso ou erro ao enviar o formulário." },
  "62": { titulo: "Campo com cara de campo", corrigir: "Dê borda ou fundo ao campo para ele não parecer texto solto." },
  "64": { titulo: "Celular primeiro", corrigir: "Escreva o estilo do celular primeiro e aumente nos breakpoints (md, lg, xl)." },
  "65": { titulo: "Testar nas larguras", corrigir: "Confira em 320, 375, 414, 768, 1024 e 1440 px." },
  "66": { titulo: "Toque confortável no celular", corrigir: "Aumente botões e links no celular (a casa usa 44 px de altura)." },
  "67": { titulo: "Letra legível", corrigir: "Texto corrido com 16 px ou mais no celular." },
  "68": { titulo: "Meta viewport", corrigir: "Use <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">." },
  "69": { titulo: "Sem rolagem para o lado", corrigir: "Nada mais largo que a tela: confira que a página não rola para o lado em 375 px." },
  "70": { titulo: "Imagem que se ajusta", corrigir: "Use max-width: 100% e altura automática nas imagens." },
  "71": { titulo: "Tabela no celular", corrigir: "Envolva a tabela com rolagem horizontal ou troque por cartões no celular." },
  "72": { titulo: "Altura da linha", corrigir: "Use entrelinha de 1,5 a 1,75 no texto corrido." },
  "73": { titulo: "Comprimento da linha", corrigir: "Limite a 65 ou 75 caracteres por linha nas telas grandes." },
  "74": { titulo: "Escala de tamanhos", corrigir: "Use uma escala fixa de tamanhos (12, 14, 16, 18, 24, 32) em vez de valores soltos." },
  "75": { titulo: "Fonte sem pulo", corrigir: "Use display=swap e uma fonte de reserva parecida para o texto não pular ao carregar." },
  "76": { titulo: "Contraste do texto", corrigir: "Texto escuro no fundo claro (ou o inverso) com contraste AA; nada de cinza sobre cinza." },
  "77": { titulo: "Título que se destaca", corrigir: "Diferencie o título do texto por tamanho e peso." },
  "78": { titulo: "Indicador de espera", corrigir: "Mostre progresso ou esqueleto proporcional à espera, com aria-busy." },
  "79": { titulo: "Estado vazio", corrigir: "Mostre mensagem e a ação que resolve quando não há conteúdo." },
  "80": { titulo: "Recuperar do erro", corrigir: "Diga o próximo passo depois de um erro (tentar de novo, falar com alguém)." },
  "81": { titulo: "Progresso em etapas", corrigir: "Mostre \"passo 2 de 4\" ou barra de progresso nos fluxos com etapas." },
  "82": { titulo: "Aviso passageiro", corrigir: "O aviso passageiro some sozinho em 3 a 5 segundos." },
  "83": { titulo: "Mensagem de sucesso", corrigir: "Confirme com uma mensagem curta (\"Enviado\")." },
  "84": { titulo: "Texto longo", corrigir: "Corte com reticências e dê um jeito de ver o texto inteiro." },
  "85": { titulo: "Formato de data", corrigir: "Use a data no formato brasileiro (dd/mm) ou relativa (\"há 2 horas\")." },
  "86": { titulo: "Formato de número", corrigir: "Use separador de milhar (1.234) ou abreviação (1,2 mil)." },
  "87": { titulo: "Conteúdo de exemplo", corrigir: "Nunca deixe texto de preenchimento (lorem ipsum): use o texto real do pacote." },
  "88": { titulo: "Liberdade no tutorial", corrigir: "Dê \"Pular\" e \"Voltar\" em qualquer tour guiado." },
  "89": { titulo: "Sugestões na busca", corrigir: "Mostre sugestões enquanto a pessoa digita na busca." },
  "90": { titulo: "Busca sem resultado", corrigir: "Mostre \"Nada encontrado\" com sugestões de outra busca." },
  "91": { titulo: "Ações em lote", corrigir: "Permita selecionar vários itens e agir de uma vez." },
  "92": { titulo: "Aviso de IA", corrigir: "Deixe claro quando o conteúdo ou o atendimento é de IA." },
  "93": { titulo: "Resposta de IA em fluxo", corrigir: "Mostre a resposta da IA chegando aos poucos." },
  "96": { titulo: "Vídeo que toca sozinho", corrigir: "Prefira clicar para tocar; com autoplay, use muted, controles e legenda, e pare fora da tela." },
  "97": { titulo: "Peso dos arquivos", corrigir: "Comprima imagens e modelos 3D e carregue sob demanda." },
  "98": { titulo: "Avaliar a resposta da IA", corrigir: "Dê um jeito de avaliar a resposta da IA (gostei, refazer)." },
  "99": { titulo: "Sensibilidade a movimento", corrigir: "Com prefers-reduced-motion, nada de parallax nem rolagem presa: mostre o estado final." },
  "100": { titulo: "Foco que não some", corrigir: "Compense as barras fixas com scroll-padding para o foco do teclado não ficar escondido." },
  "101": { titulo: "Foco sempre inteiro", corrigir: "Não deixe nenhuma parte do elemento focado coberta por barra ou aviso fixo." },
  "102": { titulo: "Aparência do foco", corrigir: "Anel de foco com pelo menos 2 px e contraste de 3:1 (outline: 2px solid; outline-offset: 2px)." },
  "103": { titulo: "Alternativa ao arrastar", corrigir: "Todo arrastar precisa de botões ou teclado como alternativa (subir, descer)." },
  "104": { titulo: "Alvo mínimo de toque", corrigir: "Alvos com pelo menos 24 por 24 px na web (a casa usa 44 px no celular)." },
  "105": { titulo: "Ajuda sempre no mesmo lugar", corrigir: "Deixe WhatsApp e contato no mesmo lugar em todas as páginas." },
  "106": { titulo: "Não pedir o mesmo dado duas vezes", corrigir: "Reaproveite o que a pessoa já informou no mesmo processo." },
  "107": { titulo: "Login acessível", corrigir: "Permita colar a senha e usar gerenciador de senhas; ofereça um jeito sem teste de memória." },
  "108": { titulo: "Carrossel com pausa", corrigir: "Dê anterior, próximo e pausar; pare no foco, ao passar o mouse e com movimento reduzido." },
  "109": { titulo: "Resumo de erros com foco", corrigir: "No envio com erro, mostre o resumo no topo do formulário, leve o foco até ele e ligue cada item ao campo." },
  "110": { titulo: "Título equilibrado", corrigir: "Limite a largura do título e use text-wrap: balance como melhoria; sem quebra de linha fixa." },
  "111": { titulo: "Palavra longa que estoura", corrigir: "Use overflow-wrap: anywhere e min-width: 0 nos filhos de flex e grid." },
  "112": { titulo: "Texto que se reorganiza", corrigir: "Nada de caixa com altura ou largura fixa cortando texto no zoom ou na tela estreita." },
  "113": { titulo: "Texto essencial inteiro", corrigir: "Título, botão, erro e aviso de segurança nunca ficam cortados: quebre a linha ou mostre o detalhe." },
  "114": { titulo: "Selo não é botão", corrigir: "Selo mostra estado (span); só vira botão quando faz uma ação." },
  "115": { titulo: "Etiquetas que quebram linha", corrigir: "Deixe as etiquetas quebrarem linha ou use \"+n\" que abre o resto." },
  "116": { titulo: "Etiqueta numa linha", corrigir: "A etiqueta cabe numa linha; se cortar, dê um jeito de ver o texto inteiro no toque." },
  "117": { titulo: "Chip clicável acessível", corrigir: "Chip clicável é button com aria-pressed, foco visível e teclado." },
  "118": { titulo: "Contagem anunciada", corrigir: "Mudança de contagem anuncia uma frase com role=\"status\" (ex.: \"3 itens no carrinho\")." },
  "119": { titulo: "Transição que pode ser cancelada", corrigir: "Cancele a animação anterior ao trocar rápido e grave o estado final direto." },
};

/** Rótulo do produto (ou o nome em inglês da base, quando falta). */
export const rotuloDoProduto = (no: string, nomeDaBase = "") => ROTULO_DO_PRODUTO[String(no)] || nomeDaBase || String(no);
export const rotuloDoEstilo = (id: string, nomeDaBase = "") => (ESTILO_EM_PORTUGUES[id] ? ESTILO_EM_PORTUGUES[id].rotulo : nomeDaBase || id);
export const rotuloDoPadrao = (id: string, nomeDaBase = "") => ROTULO_DO_PADRAO[id] || nomeDaBase || id;
export const severidadeDaRegra = (bruta: string): SeveridadeDaRegra => SEVERIDADE_DA_BASE[bruta] || "media";
