/**
 * Gerado por scripts/uiux/importar-base.mjs a partir de UI UX Pro Max 2.15.0 (MIT, Next Level Builder, github.com/nextlevelbuilder/ui-ux-pro-max-skill). Não edite à mão.
 * Fonte: workers/motor-codigo/vendor/ui-ux-pro-max/data/landing.csv (SHA-256 9a2edd3bb676c2a58f00ade7a062e285222d4297bfd847c8d5b056f0dbbf52d0), 34 linhas.
 */

/** Chave nossa -> coluna de landing.csv (o teste de igualdade usa o mesmo mapa). */
export const COLUNAS = {"no":"No","nome":"Pattern Name","palavras":"Keywords","ordem":"Section Order","cta":"Primary CTA Placement","id":"Pattern ID","apelidos":"Aliases"} as const;

export type PadraoDaBase = { no: string; nome: string; palavras: string; ordem: string; cta: string; id: string; apelidos: string };

const LINHAS: string[][] = [
  ["1","Hero + Features + CTA","hero, hero-centric, hero-centric design, features, feature-rich, feature-rich showcase, cta, call-to-action","Hero with headline/image > Value prop > Key features (3-5) > CTA section > Footer","Hero (sticky) + Bottom","hero-features-cta",""],
  ["2","Hero + Testimonials + CTA","hero, testimonials, social-proof, social-proof-focused, social proof focused, trust, reviews, cta, carousel accessibility, keyboard accessible carousel, pause auto rotation, reduced motion final state","Hero > Problem statement > Solution overview > Testimonials carousel > CTA","Hero (sticky) + Post-testimonials","hero-testimonials-cta","Conversion-Optimized + Social Proof|Feature-Rich + Social Proof|Feature-Rich Showcase + Social Proof|Hero-Centric + Social Proof|Minimal & Direct + Social Proof|Social Proof + Conversion|Social Proof + Feature-Rich|Social Proof-Focused|Social Proof-Focused + Conversion|Social Proof-Focused + Feature-Rich|Storytelling + Social Proof|Storytelling-Driven + Social Proof"],
  ["3","Product Demo + Features","demo, product-demo, features, showcase, interactive, interactive-product-demo, interactive product demo","Hero > Product video/mockup (center) > Feature breakdown per section > Comparison (optional) > CTA","Video center + CTA right/bottom","product-demo-features","Conversion-Optimized + Demo|Feature-Rich Showcase + Demo|Feature-Rich Showcase + Interactive Demo|Interactive Demo + Feature-Rich|Interactive Demo + Minimal|Interactive Product Demo|Interactive Product Demo + Minimal|Interactive Product Demo + Social Proof|Interactive Product Demo + Storytelling|Minimal & Direct + Demo|Social Proof-Focused + Demo"],
  ["4","Minimal Single Column","minimal, simple, direct, minimal & direct, minimal-direct, single-column, clean","Hero headline > Short description > Benefit bullets (3 max) > CTA > Footer","Center, large CTA button","minimal-single-column","Minimal & Direct"],
  ["5","Funnel (3-Step Conversion)","funnel, conversion, conversion-optimized, conversion optimized, steps, wizard, onboarding","Hero > Step 1 (problem) > Step 2 (solution) > Step 3 (action) > CTA progression","Each step: mini-CTA. Final: main CTA","funnel-3-step-conversion","Conversion + Feature-Rich|Conversion-Optimized|Conversion-Optimized + Feature-Rich|Feature-Rich + Conversion|Hero-Centric + Conversion|Minimal & Direct + Conversion|Minimal + Conversion"],
  ["6","Comparison Table + CTA","comparison, table, compare, versus, cta","Hero > Problem intro > Comparison table (product vs competitors) > Pricing (optional) > CTA","Table: Right column. CTA: Below table","comparison-table-cta",""],
  ["7","Lead Magnet + Form","lead, form, signup, capture, email, magnet","Hero (benefit headline) > Lead magnet preview (ebook cover, checklist, etc) > Form (minimal fields) > CTA submit","Form CTA: Submit button","lead-magnet-form",""],
  ["8","Pricing Page + CTA","pricing, plans, tiers, comparison, cta","Hero (pricing headline) > Price comparison cards > Feature comparison table > FAQ section > Final CTA","Each card: CTA button. Sticky CTA in nav","pricing-page-cta",""],
  ["9","Video-First Hero","video, hero, media, visual, engaging","Hero with video background > Key features overlay > Benefits section > CTA","Overlay on video (center/bottom) + Bottom section","video-first-hero",""],
  ["10","Scroll-Triggered Storytelling","storytelling, scroll, narrative, story, immersive","Intro hook > Chapter 1 (problem) > Chapter 2 (journey) > Chapter 3 (solution) > Climax CTA","End of each chapter (mini) + Final climax CTA","scroll-triggered-storytelling","Storytelling + Data|Storytelling + Feature-Rich|Storytelling + Hero-Centric|Storytelling-Driven|Storytelling-Driven + Feature-Rich|Storytelling-Driven + Hero|Storytelling-Driven + Hero-Centric"],
  ["11","AI Personalization Landing","ai, personalization, smart, recommendation, dynamic","Dynamic hero (personalized) > Relevant features > Tailored testimonials > Smart CTA","Context-aware placement based on user segment","ai-personalization-landing",""],
  ["12","Waitlist/Coming Soon","waitlist, coming-soon, launch, early-access, notify, countdown accessibility, pause animation, reduced motion final state, verified waitlist count","Hero with countdown > Product teaser/preview > Email capture form > Social proof (waitlist count)","Email form prominent (above fold) + Sticky form on scroll","waitlist-coming-soon",""],
  ["13","Comparison Table Focus","comparison, table, versus, compare, features","Hero (problem statement) > Comparison matrix (you vs competitors) > Feature deep-dive > Winner CTA","After comparison table (highlighted row) + Bottom","comparison-table-focus",""],
  ["14","Pricing-Focused Landing","pricing, price, cost, plans, subscription","Hero (value proposition) > Pricing cards (3 tiers) > Feature comparison > FAQ > Final CTA","Each pricing card + Sticky CTA in nav + Bottom","pricing-focused-landing",""],
  ["15","App Store Style Landing","app, mobile, download, store, install, carousel accessibility, keyboard accessible carousel, pause auto rotation, reduced motion final state, single pointer buttons","Hero with device mockup > Screenshots carousel > Features with icons > Reviews/ratings > Download CTAs","Download buttons prominent (App Store + Play Store) throughout","app-store-style-landing",""],
  ["16","FAQ/Documentation Landing","faq, documentation, help, support, questions, faq/documentation, knowledge base","Hero with search bar > Popular categories > FAQ accordion > Contact/support CTA","Search bar prominent + Contact CTA for unresolved questions","faq-documentation-landing","FAQ + Minimal|Feature-Rich + Documentation|Minimal + Documentation"],
  ["17","Immersive/Interactive Experience","immersive, interactive, experience, 3d, animation, immersive/interactive experience","Full-screen interactive element > Guided product tour > Key benefits revealed > CTA after completion","After interaction complete + Skip option for impatient users","immersive-interactive-experience","Immersive + Feature-Rich|Immersive + Interactive"],
  ["18","Event/Conference Landing","event, conference, meetup, registration, schedule, hero-centric design, hero-centric, countdown accessibility, pause animation, reduced motion final state","Hero (date/location/countdown) > Speakers grid > Agenda/schedule > Sponsors > Register CTA","Register CTA sticky + After speakers + Bottom","event-conference-landing",""],
  ["19","Product Review/Ratings Focused","reviews, ratings, testimonials, social-proof, social-proof-focused, stars","Hero (product + aggregate rating) > Rating breakdown > Individual reviews > Buy/CTA","After reviews summary + Buy button alongside reviews","product-review-ratings-focused",""],
  ["20","Community/Forum Landing","community, forum, social, members, discussion, verified member count, live update accessibility, pause updates, reduced motion final state","Hero (community value prop) > Popular topics/categories > Active members showcase > Join CTA","Join button prominent + After member showcase","community-forum-landing",""],
  ["21","Before-After Transformation","before-after, transformation, results, comparison, accessible drag interaction, drag single pointer alternative, keyboard drag alternative","Hero (problem state) > Transformation slider/comparison > How it works > Results CTA","After transformation reveal + Bottom","before-after-transformation",""],
  ["22","Marketplace / Directory","marketplace, directory, search, listing, carousel accessibility, keyboard accessible carousel, pause auto rotation, reduced motion final state, marketplace carousel, keyboard carousel controls","Hero (Search focused) > Categories > Featured Listings > Trust/Safety > CTA (Become a host/seller)","Hero Search Bar + Navbar 'List your item'","marketplace-directory",""],
  ["23","Newsletter / Content First","newsletter, content, writer, blog, subscribe, minimal & direct, minimal-direct, verified subscriber count, dated social proof","Hero (Value Prop + Form) > Recent Issues/Archives > Social Proof (Subscriber count) > About Author","Hero inline form + Sticky header form","newsletter-content-first",""],
  ["24","Webinar Registration","webinar, registration, event, training, live, webinar ticker accessibility, pause ticker, verified seat availability, verified live status, reduced motion final state","Hero (Topic + Timer + Form) > What you'll learn > Speaker Bio > Urgency/Bonuses > Form (again)","Hero (Right side form) + Bottom anchor","webinar-registration",""],
  ["25","Enterprise Gateway","enterprise, corporate, gateway, solutions, portal, trust, authority, trust & authority, carousel accessibility, keyboard accessible carousel, pause auto rotation, reduced motion final state","Hero (Video/Mission) > Solutions by Industry > Solutions by Role > Client Logos > Contact Sales","Contact Sales (Primary) + Login (Secondary)","enterprise-gateway","Data-Dense + Drill-Down|Data-Dense + Storytelling|Data-Dense Dashboard"],
  ["26","Portfolio Grid","portfolio, grid, showcase, gallery, masonry, portfolio grid + visuals","Hero (Name/Role) > Project Grid (Masonry) > About/Philosophy > Contact","Project Card Hover + Footer Contact","portfolio-grid","Portfolio + Hero-Centric"],
  ["27","Horizontal Scroll Journey","horizontal, scroll, journey, gallery, storytelling, panoramic, storytelling-driven","Intro (Vertical) > The Journey (Horizontal Track) > Detail Reveal > Vertical Footer","Floating Sticky CTA or End of Horizontal Track","horizontal-scroll-journey",""],
  ["28","Bento Grid Showcase","bento, grid, features, modular, apple-style, showcase, feature-rich showcase","Hero > Bento Grid (Key Features) > Detail Cards > Tech Specs > CTA","Floating Action Button or Bottom of Grid","bento-grid-showcase",""],
  ["29","Interactive 3D Configurator","3d, configurator, customizer, interactive, product, interactive product demo, accessible drag interaction, drag single pointer alternative, keyboard drag alternative","Hero (Configurator) > Feature Highlight (synced) > Price/Specs > Purchase","Inside Configurator UI + Sticky Bottom Bar","interactive-3d-configurator",""],
  ["30","AI-Driven Dynamic Landing","ai, dynamic, personalized, adaptive, generative","Prompt/Input Hero > Generated Result Preview > How it Works > Value Prop","Input Field (Hero) + 'Try it' Buttons","ai-driven-dynamic-landing",""],
  ["31","Feature-Rich Showcase","feature-rich, feature-rich showcase, features, showcase, product showcase","Hero (value prop) > Feature grid/cards (4-6) > Use cases or benefits > Social proof or logos > CTA","Hero (sticky) + After features + Bottom","feature-rich-showcase","Feature-Rich + Data|Showcase + Feature-Rich"],
  ["32","Hero-Centric Design","hero-centric, hero-centric design, hero-first, hero above fold","Full-bleed Hero (headline + visual) > Single value prop strip > Key benefit or proof > Primary CTA","Hero dominant (center/bottom) + Sticky nav CTA","hero-centric-design","Feature-Rich Showcase + Hero-Centric|Hero-Centric + Feature-Rich|Hero-Centric Design + Feature-Rich"],
  ["33","Trust & Authority + Conversion","trust & authority, trust, authority, conversion, credibility, enterprise, carousel accessibility, keyboard accessible carousel, pause auto rotation, reduced motion final state","Hero (mission/credibility) > Proof (logos, certs, stats) > Solution overview > Clear CTA path","Contact Sales / Get Quote (primary) + Nav","trust-authority-conversion","Conversion + Trust|Conversion-Optimized + Trust|Data + Trust|Feature-Rich Showcase + Trust|Hero-Centric + Trust|Social Proof-Focused + Trust|Storytelling + Trust|Trust & Authority|Trust & Authority + Accessible|Trust & Authority + Conversion-Optimized|Trust & Authority + Feature|Trust & Authority + Feature-Rich|Trust & Authority + Minimal|Trust & Authority + Social Proof"],
  ["34","Real-Time / Operations Landing","real-time, real-time monitor, operations, dashboard, telemetry, live data, live ticker accessibility, pause live updates, verified live status, reduced motion final state","Hero (product + live preview or status) > Key metrics/indicators > How it works > CTA (Start trial / Contact)","Primary CTA in nav + After metrics","real-time-operations-landing","Feature-Rich + Real-Time|Feature-Rich Showcase + Real-Time|Real-Time + Feature-Rich|Real-Time Monitoring|Trust & Authority + Real-Time"],
];

export const PADROES_DA_BASE: PadraoDaBase[] = LINHAS.map((l) => ({ no: l[0], nome: l[1], palavras: l[2], ordem: l[3], cta: l[4], id: l[5], apelidos: l[6] }));
