/**
 * Gerado por scripts/uiux/importar-base.mjs a partir de UI UX Pro Max 2.15.0 (MIT, Next Level Builder, github.com/nextlevelbuilder/ui-ux-pro-max-skill). Não edite à mão.
 * Fonte: workers/motor-codigo/vendor/ui-ux-pro-max/data/ux-guidelines.csv (SHA-256 ff81ec613f70ba9fc3fcce52dbe4ae35d44b2079dbe6dc066d2d6e38c28facd5), 119 linhas.
 */

/** Chave nossa -> coluna de ux-guidelines.csv (o teste de igualdade usa o mesmo mapa). */
export const COLUNAS = {"no":"No","categoria":"Category","problema":"Issue","plataforma":"Platform","codigoBom":"Code Example Good","severidade":"Severity"} as const;

export type RegraDeUxDaBase = { no: string; categoria: string; problema: string; plataforma: string; codigoBom: string; severidade: string };

const LINHAS: string[][] = [
  ["1","Navigation","Smooth Scroll","Web","html { scroll-behavior: smooth; }","High"],
  ["2","Navigation","Sticky Navigation","Web","pt-20 (if nav is h-20)","Medium"],
  ["3","Navigation","Active State","All","text-primary border-b-2","Medium"],
  ["4","Navigation","Back Button","Mobile","history.pushState()","High"],
  ["5","Navigation","Deep Linking","All","Use query params or hash","Medium"],
  ["6","Navigation","Breadcrumbs","Web","Home > Category > Product","Low"],
  ["7","Animation","Excessive Motion","All","Single hero animation","High"],
  ["8","Animation","Duration Timing","All","transition-colors duration-200","Medium"],
  ["9","Animation","Reduced Motion","All","@media (prefers-reduced-motion: reduce)","High"],
  ["10","Animation","Loading States","All","animate-pulse skeleton","High"],
  ["11","Animation","Hover vs Tap","All","onClick handler","High"],
  ["12","Animation","Continuous Animation","All","animate-spin on loader","Medium"],
  ["13","Animation","Transform Performance","Web","transform: translateY()","Medium"],
  ["14","Animation","Easing Functions","All","ease-out for entry; linear for spinner","Low"],
  ["15","Layout","Z-Index Management","Web","z-10 z-20 z-50","High"],
  ["16","Layout","Overflow Hidden","Web","overflow-auto with scroll","Medium"],
  ["17","Layout","Fixed Positioning","Web","Fixed nav + fixed bottom with gap","Medium"],
  ["18","Layout","Stacking Context","Web","Parent with z-index isolates children","Medium"],
  ["19","Layout","Content Jumping","Web","aspect-ratio for media; stable count slot for badges","High"],
  ["20","Layout","Viewport Units","Web","min-h-dvh or min-h-screen","Medium"],
  ["21","Layout","Container Width","Web","max-w-prose or max-w-3xl","Medium"],
  ["22","Touch","Touch Target Size","Mobile","iOS 44pt; Android 48dp; Web 24 CSS px plus WCAG exceptions","High"],
  ["23","Touch","Touch Spacing","Mobile","gap-2 between buttons","Medium"],
  ["24","Touch","Gesture Conflicts","Mobile","Vertical scroll primary","Medium"],
  ["25","Touch","Tap Delay","Mobile","touch-action: manipulation","Medium"],
  ["26","Touch","Pull to Refresh","Mobile","overscroll-behavior: contain","Low"],
  ["27","Touch","Haptic Feedback","Mobile","navigator.vibrate(10)","Low"],
  ["28","Interaction","Focus States","All","focus:ring-2 focus:ring-blue-500","High"],
  ["29","Interaction","Hover States","Web","hover:bg-gray-100 cursor-pointer","Medium"],
  ["30","Interaction","Active States","All","active:scale-95","Medium"],
  ["31","Interaction","Disabled States","All","opacity-50 cursor-not-allowed","Medium"],
  ["32","Interaction","Loading Buttons","All","disabled={loading} spinner","High"],
  ["33","Interaction","Error Feedback","All","Red border + error message","High"],
  ["34","Interaction","Success Feedback","All","Toast notification or checkmark","Medium"],
  ["35","Interaction","Confirmation Dialogs","All","Are you sure modal","High"],
  ["36","Accessibility","Color Contrast","All","#333 on white (7:1)","High"],
  ["37","Accessibility","Color Only","All","Red text + error icon","High"],
  ["38","Accessibility","Alt Text","All","alt='Dog playing in park'","High"],
  ["39","Accessibility","Heading Hierarchy","Web","h1 then h2 then h3","Medium"],
  ["40","Accessibility","ARIA Labels","All","aria-label='Close menu'","High"],
  ["41","Accessibility","Keyboard Navigation","Web","tabIndex for custom order","High"],
  ["42","Accessibility","Screen Reader","All","<nav> <main> <article>","Medium"],
  ["43","Accessibility","Form Labels","All","<label for='email'>","High"],
  ["44","Accessibility","Error Messages","All","role='alert'","High"],
  ["45","Accessibility","Skip Links","Web","Skip to main content link","Medium"],
  ["46","Performance","Image Optimization","All","srcset with multiple sizes","High"],
  ["47","Performance","Lazy Loading","All","loading='lazy'","Medium"],
  ["48","Performance","Code Splitting","Web","dynamic import()","Medium"],
  ["49","Performance","Caching","Web","Cache-Control headers","Medium"],
  ["50","Performance","Font Loading","Web","font-display: swap","Medium"],
  ["51","Performance","Third Party Scripts","Web","async or defer attribute","Medium"],
  ["52","Performance","Bundle Size","Web","Bundle analyzer","Medium"],
  ["53","Performance","Render Blocking","Web","Critical CSS inline","Medium"],
  ["54","Forms","Input Labels","All","<label>Email</label><input>","High"],
  ["55","Forms","Error Placement","All","<input aria-describedby=\"email-error\"><p id=\"email-error\">Enter an email address</p>","High"],
  ["56","Forms","Inline Validation","All","onBlur validation","Medium"],
  ["57","Forms","Input Types","All","type='email'","Medium"],
  ["58","Forms","Autofill Support","Web","autocomplete='email'","Medium"],
  ["59","Forms","Required Indicators","All","* required indicator","Medium"],
  ["60","Forms","Password Visibility","All","Show/hide password button","Medium"],
  ["61","Forms","Submit Feedback","All","Loading -> Success message","High"],
  ["62","Forms","Input Affordance","All","Border/background on inputs","Medium"],
  ["63","Forms","Mobile Keyboards","Mobile","inputmode='numeric'","Medium"],
  ["64","Responsive","Mobile First","Web","Default mobile + md: lg: xl:","Medium"],
  ["65","Responsive","Breakpoint Testing","Web","Multiple device testing","Medium"],
  ["66","Responsive","Touch Friendly","Web","Larger buttons on mobile","High"],
  ["67","Responsive","Readable Font Size","All","text-base or larger","High"],
  ["68","Responsive","Viewport Meta","Web","<meta name='viewport'...>","High"],
  ["69","Responsive","Horizontal Scroll","Web","max-w-full overflow-x-hidden","High"],
  ["70","Responsive","Image Scaling","Web","max-w-full h-auto","Medium"],
  ["71","Responsive","Table Handling","Web","overflow-x-auto wrapper","Medium"],
  ["72","Typography","Line Height","All","leading-relaxed (1.625)","Medium"],
  ["73","Typography","Line Length","Web","max-w-prose","Medium"],
  ["74","Typography","Font Size Scale","All","Type scale (12 14 16 18 24 32)","Medium"],
  ["75","Typography","Font Loading","Web","font-display: swap + similar fallback","Medium"],
  ["76","Typography","Contrast Readability","All","text-gray-900 on white","High"],
  ["77","Typography","Heading Clarity","All","Bold + larger size","Medium"],
  ["78","Feedback","Loading Indicators","All","Stable skeleton or progress with aria-busy","High"],
  ["79","Feedback","Empty States","All","No items yet. Create one!","Medium"],
  ["80","Feedback","Error Recovery","All","Try again button + help link","Medium"],
  ["81","Feedback","Progress Indicators","All","Step 2 of 4 indicator","Medium"],
  ["82","Feedback","Toast Notifications","All","Auto-dismiss toast","Medium"],
  ["83","Feedback","Confirmation Messages","All","Saved successfully toast","Medium"],
  ["84","Content","Truncation","All","line-clamp-2 with expand","Medium"],
  ["85","Content","Date Formatting","All","2 hours ago or locale format","Low"],
  ["86","Content","Number Formatting","All","1.2K or 1,234","Low"],
  ["87","Content","Placeholder Content","All","Real sample content","Low"],
  ["88","Onboarding","User Freedom","All","Skip Tutorial button","Medium"],
  ["89","Search","Autocomplete","Web","Debounced fetch + dropdown","Medium"],
  ["90","Search","No Results","Web","Try searching for X instead","Medium"],
  ["91","Data Entry","Bulk Actions","Web","Checkbox column + Action bar","Low"],
  ["92","AI Interaction","Disclaimer","All","AI Assistant label","High"],
  ["93","AI Interaction","Streaming","All","Typewriter effect","Medium"],
  ["94","Spatial UI","Gaze Hover","VisionOS","hoverEffect()","High"],
  ["95","Spatial UI","Depth Layering","VisionOS",".glassBackgroundEffect()","Medium"],
  ["96","Sustainability","Auto-Play Video","Web","<video controls preload=\"none\"><track kind=\"captions\" /></video>","Medium"],
  ["97","Sustainability","Asset Weight","Web","Draco compression","Medium"],
  ["98","AI Interaction","Feedback Loop","All","Feedback component","Low"],
  ["99","Accessibility","Motion Sensitivity","All","@media (prefers-reduced-motion)","High"],
  ["100","Accessibility","Focus Not Obscured (Minimum)","Web","scroll-padding-top: var(--header-height)","High"],
  ["101","Accessibility","Focus Not Obscured (Enhanced)","Web","close persistent overlay before focus moves behind it","Medium"],
  ["102","Accessibility","Focus Appearance","Web","outline: 2px solid currentColor; outline-offset: 2px","Medium"],
  ["103","Accessibility","Dragging Movements","All","Move up and Move down buttons beside drag handle","High"],
  ["104","Accessibility","Target Size (Minimum)","Web","min-width: 24px; min-height: 24px","High"],
  ["105","Accessibility","Consistent Help","All","shared header help menu","Medium"],
  ["106","Forms","Redundant Entry","All","reuse confirmed shipping address","Medium"],
  ["107","Security / Accessibility","Accessible Authentication (Minimum)","All","autocomplete=\"current-password\" and paste allowed","Critical"],
  ["108","Animation","Auto-Rotating Content Controls","All","button aria-label=\"Pause carousel\"","High"],
  ["109","Forms / Accessibility","Focusable Error Summary","Web","<div role=\"alert\" tabindex=\"-1\" aria-labelledby=\"error-title\"><h2 id=\"error-title\">There is a problem</h2><a href=\"#email\">Enter an email address</a></div>","High"],
  ["110","Typography","Heading Line Balance","Web",".hero-title { max-inline-size: 20ch; text-wrap: balance; }","Medium"],
  ["111","Layout","Long Token Wrapping","Web",".token { min-inline-size: 0; overflow-wrap: anywhere; }","High"],
  ["112","Accessibility","Text Reflow and Spacing","Web",".copy { inline-size: min(100%, 65ch); height: auto; line-height: 1.5; }","Critical"],
  ["113","Content","Essential Text Truncation","All","Action label wraps or opens full details","Critical"],
  ["114","Content","Compact Label Semantics","All","<span class='status'>Pending</span>","High"],
  ["115","Layout","Chip Collection Reflow","All","<div class='chip-list'>{chips}</div> with flex-wrap","High"],
  ["116","Content","Compact Label Overflow","All","Flexible label with min-width 0 and an operable full-value disclosure","High"],
  ["117","Accessibility","Compact Control Semantics","Web","<button aria-pressed='true'>Open now</button>","Critical"],
  ["118","Accessibility","Contextual Live Badge Updates","Web","<span role='status' aria-atomic='true'>3 items in cart</span>","High"],
  ["119","Animation","Cancellable State Transitions","Web","previous?.cancel(); setSelected(next)","High"],
];

export const REGRAS_DE_UX_DA_BASE: RegraDeUxDaBase[] = LINHAS.map((l) => ({ no: l[0], categoria: l[1], problema: l[2], plataforma: l[3], codigoBom: l[4], severidade: l[5] }));
