# -*- coding: utf-8 -*-
"""Gera docs/mesa-ads/v2/biblioteca-padroes.json e seed_biblioteca_padroes.sql.

Padrões de estudo (E0) por nicho, sem marca de terceiro e sem prova inventada.
Rodar da raiz do repo: python -B docs/mesa-ads/pesquisa/ferramentas/gerar_biblioteca.py
ids-conhecimento.json guarda os ids de ESTILOS_VISUAIS, NICHOS e
OBJETIVOS_DE_CAMPANHA de supabase/functions/_shared/conhecimento-ads.ts;
regerar esse arquivo se o conhecimento mudar.
"""
import json
import os
import sys

AQUI = os.path.dirname(os.path.abspath(__file__))
RAIZ = os.path.abspath(os.path.join(AQUI, "..", "..", "..", ".."))
IDS = json.load(open(os.path.join(AQUI, "ids-conhecimento.json"), encoding="utf-8"))
ESTILOS = {e["id"]: e for e in IDS["estilos"]}
NICHOS = {n["id"]: n["nome"] for n in IDS["nichos"]}
OBJETIVOS = set(IDS["objetivos"])
CTAS = {"Saiba mais", "Enviar mensagem", "Fale conosco", "Cadastre-se", "Comprar agora", "Agendar", "Solicitar orçamento", "Ver menu", "Ligar agora", "Baixar", "Obter oferta"}

TECNICA = {
    "oferta_direta": "Oferta com condição real e próximo passo (estruturas de copy: oferta) e prova antes da explicação (técnica 9).",
    "tipografia_gigante": "Afirmação contraintuitiva ou objeção como pauta (técnicas 10 e 12) com contraste de escala.",
    "close_extremo": "Resultado demonstrável pelo detalhe (técnica 8) e prova antes da explicação (técnica 9).",
    "objeto_inesperado": "Incongruência com sentido (técnica 4) e mapa do clichê (técnica 2).",
    "metafora_visual": "Metáfora concreta (técnica 3).",
    "comparacao_lado_a_lado": "Comparação justa (técnica 11).",
    "nos_contra_eles": "Comparação justa (técnica 11) com critério verificável.",
    "depoimento_citacao": "Prova antes da explicação (técnica 9) com linguagem real do cliente (técnica 13, só depoimento autorizado).",
    "lista_checklist": "Objeção como pauta (técnica 10) e curiosidade com entrega (técnica 12).",
    "ugc_nativo": "Dor de contexto (técnica 7) com execução nativa e real.",
    "bastidor_real": "Resultado demonstrável (técnica 8) pelo processo real.",
    "demonstracao_etapas": "Resultado demonstrável (técnica 8) e sequência que reduz o esforço percebido.",
    "antes_depois": "Resultado demonstrável (técnica 8) com comparação nas mesmas condições (técnica 11).",
    "moldura_de_app": "Linguagem de pesquisa (técnica 13) em moldura estilizada; usar só se a ficha permitir.",
    "objecao_na_manchete": "Objeção como pauta (técnica 10).",
    "numero_em_destaque": "Prova antes da explicação (técnica 9) com número real, período e fonte.",
    "produto_heroi_cor": "Mapa do clichê (técnica 2): sair do fundo branco de catálogo, produto como herói.",
    "editorial_manchete": "Curiosidade com entrega (técnica 12).",
    "humor_situacao": "Contraste emocional (técnica 6) e dor de contexto (técnica 7).",
    "local_e_bairro": "Situação antes de categoria (técnica 1) com a região atendida.",
    "pilha_de_oferta": "Oferta com entregáveis visíveis e ancoragem real (montagem de oferta).",
    "rosto_e_olhar": "Adaptação por motivação (técnica 17) e confiança pela pessoa real.",
}

FONTE = "Padrão da agência Aceleriq (Mesa Ads v2, 24/09/2026), derivado de docs/mesa-ads/pesquisa (DOSSIE-CRIATIVOS.md e PESQUISA-V2.md) e de _shared/conhecimento-ads.ts. Sem marca de terceiros e sem veiculação."
SUBSTITUIR = "Foto, textos, números, preço, prazo e provas pelos reais do cliente. O gancho verbal é exemplo: reescrever com a linguagem do público. O que está entre colchetes só entra confirmado pela equipe."

# (titulo, estilo, objetivo, situacao, gancho_visual, gancho_verbal, texto_apoio, mecanismo, prova_necessaria, cta, destino, riscos, tags extras)
P = {}

P["estetica"] = [
    ("Estética: avaliação antes da agulha", "objecao_na_manchete", "agendamento",
     "Pessoa com vontade de fazer um procedimento, com medo de ficar artificial e sem saber o que serve para o caso dela.",
     "A pergunta do comprador entre aspas em letras grandes no topo; embaixo, bloco na cor da marca com a resposta e foto real da profissional na sala de avaliação.",
     "Vou ficar artificial?",
     "Toda aplicação começa por uma avaliação com a profissional responsável. Você entende o plano antes de decidir.",
     "Objeção real vira manchete e é respondida pelo processo de avaliação.",
     "Avaliação realmente oferecida; registro profissional da responsável; foto real e autorizada.",
     "Agendar", "WhatsApp ou agenda online com a avaliação como primeira mensagem.",
     "Sem promessa de resultado; sem afirmar característica física de quem vê; público 18+.", ["objecao", "avaliacao"]),
    ("Estética: quem aplica faz diferença", "rosto_e_olhar", "mensagens",
     "Público compara preço de procedimento sem saber comparar quem faz.",
     "Close médio da profissional real olhando para a manchete, ambiente claro, selo pequeno com o registro profissional.",
     "Quem aplica faz toda a diferença",
     "Formação, protocolo e quem responde por você depois. Pergunte antes de escolher.",
     "Autoridade ligada à dúvida do comprador (quem faz), não biografia.",
     "Formação e registro reais da profissional; protocolo de segurança real.",
     "Enviar mensagem", "WhatsApp com a mensagem pronta: quero saber quem faz e como é.",
     "Sem promessa de resultado; sem comparar com clínica nomeada.", ["autoridade"]),
    ("Estética: bastidor do protocolo", "bastidor_real", "seguidores",
     "Seguidora em potencial quer ver como a clínica trabalha antes de confiar.",
     "Foto real do preparo: materiais lacrados sendo abertos, luvas, bancada limpa, luz natural; manchete em bloco de cor.",
     "Veja o que acontece antes do procedimento",
     "No perfil mostramos o passo a passo de cada protocolo, sem filtro.",
     "Bastidor como prova de cuidado e segurança.",
     "Fotos reais do protocolo da clínica.",
     "Saiba mais", "Perfil do Instagram com destaques do protocolo.",
     "Sem agulha em pele de forma chocante; sem sangue; sem resultado prometido.", ["bastidor"]),
    ("Estética: checklist para escolher a clínica", "lista_checklist", "leads",
     "Pessoa pesquisando clínicas e sem critério para escolher.",
     "Título grande e 4 checks grandes na cor da marca; foto real da recepção num terço do quadro.",
     "4 perguntas antes de escolher sua clínica",
     "Registro de quem aplica, produto usado, avaliação e retorno. Receba o guia.",
     "Critério de escolha dado de graça posiciona a clínica como a que cumpre todos.",
     "A clínica cumpre de fato cada item da lista.",
     "Cadastre-se", "Formulário instantâneo que entrega o guia e pergunta o interesse.",
     "Não atacar concorrente; não insinuar insegurança de outras clínicas.", ["guia", "isca"]),
    ("Estética: natural é técnica", "tipografia_gigante", "mensagens",
     "Público consciente da solução com receio de exagero.",
     "Frase gigante em duas linhas com a palavra técnica na cor de destaque, fundo chapado claro da marca, um instrumento real pequeno sobre a letra.",
     "Natural é técnica, não sorte",
     "Planejamento feito na avaliação, com a quantidade certa para o objetivo combinado.",
     "Afirmação contraintuitiva que reposiciona o medo de ficar artificial como falta de técnica.",
     "Método de planejamento real da clínica.",
     "Enviar mensagem", "WhatsApp.",
     "Sem antes e depois; sem promessa de resultado.", ["contraintuitivo"]),
]

P["odontologia"] = [
    ("Odontologia: plano antes do primeiro dente", "demonstracao_etapas", "agendamento",
     "Paciente adia o tratamento com medo de orçamento sem fim.",
     "Três quadros numerados: avaliação com imagem, plano impresso com etapas, início do tratamento; setas grossas na cor da marca.",
     "Plano completo antes de começar",
     "Na avaliação você recebe as etapas, o prazo estimado e as formas de pagamento.",
     "Demonstrar o processo reduz o medo do desconhecido e do orçamento aberto.",
     "Processo real de avaliação e plano da clínica.",
     "Agendar", "Agenda online ou WhatsApp.",
     "Nome e CRO do responsável na peça; divulgação de valores conforme o Código de Ética Odontológica.", ["processo"]),
    ("Odontologia: vai doer?", "objecao_na_manchete", "mensagens",
     "Pessoa com medo de dor que nunca pergunta nada ao dentista.",
     "A pergunta entre aspas em tamanho gigante, resposta curta abaixo na cor de destaque, foto real do consultório claro.",
     "Vai doer? A gente responde antes",
     "Explicamos anestesia, tempo e cada etapa antes de começar. Mande sua dúvida.",
     "Objeção de medo respondida com processo e conversa.",
     "Protocolo real de atendimento; resposta dada pelo dentista responsável.",
     "Enviar mensagem", "WhatsApp.",
     "Sem prometer ausência total de dor; sem atributo pessoal.", ["medo", "objecao"]),
    ("Odontologia: o dentista do bairro tem nome", "rosto_e_olhar", "reconhecimento",
     "Moradores da região não sabem quem é o dentista do bairro.",
     "Dentista real sorrindo em close médio, olhar para a manchete, fundo sólido da marca, nome e CRO legíveis.",
     "O dentista do [bairro] tem nome",
     "Conheça quem vai te atender, a estrutura e como funciona a primeira consulta.",
     "Humanização local: rosto conhecido reduz desconfiança.",
     "Foto real e autorizada do dentista; nome e CRO.",
     "Saiba mais", "Perfil do Instagram ou página da clínica.",
     "Nome e CRO na peça (Resolução CFO 196/2019).", ["local", "humanizacao"]),
    ("Odontologia: caso próprio concluído", "antes_depois", "agendamento",
     "Paciente quer ver trabalho real da clínica antes de marcar.",
     "Duas fotos do mesmo caso próprio, mesmo ângulo e mesma luz, rótulos grandes, nome e CRO na base.",
     "Caso real, feito aqui",
     "Cada caso é único: na avaliação mostramos o que é possível no seu.",
     "Prova visual de trabalho próprio com limite explícito.",
     "Caso próprio com termo de consentimento assinado; nome e CRO do responsável.",
     "Agendar", "WhatsApp.",
     "Risco alto: só caso próprio com consentimento (CFO 196/2019), sem prometer resultado igual, conferir regras atuais do CRO do estado; público 18+ recomendado.", ["prova", "caso"]),
    ("Odontologia: o que a avaliação inclui", "lista_checklist", "leads",
     "Paciente acha que avaliação é só uma olhada rápida.",
     "Checklist com 4 itens em checks grandes; foto real do equipamento de imagem num terço do quadro.",
     "O que sua avaliação inclui aqui",
     "Exame clínico, imagem quando indicada, plano por etapas e tempo para perguntas.",
     "Tornar visível o que está incluso aumenta o valor percebido.",
     "Itens reais da avaliação da clínica.",
     "Cadastre-se", "Formulário instantâneo com horário preferido.",
     "Sem preço se as regras do conselho restringirem; sem promessa.", ["entregaveis"]),
]

P["advocacia"] = [
    ("Advocacia: esse direito tem prazo", "tipografia_gigante", "leads",
     "Pessoa com direito trabalhista, previdenciário ou de consumo sem saber que existe prazo.",
     "Frase gigante sobre fundo chapado da marca, a palavra prazo em cor de destaque, ampulheta real pequena quebrando a grade.",
     "Esse direito tem prazo",
     "Entenda em linguagem simples quais prazos existem e quando procurar orientação.",
     "Informação útil com consequência real (prazo), sem captação direta.",
     "Base legal citada corretamente; inscrição na OAB de quem assina.",
     "Saiba mais", "Página ou material informativo.",
     "Provimento 205/2021 da OAB: informativo, sem promessa de resultado, sem preço, sem captação; sem atributo pessoal.", ["informativo", "prazo"]),
    ("Advocacia: documentos para separar", "lista_checklist", "leads",
     "Pessoa que vai procurar orientação jurídica e não sabe o que levar.",
     "Checklist com 4 documentos em ícones grandes e uma pasta real fotografada.",
     "4 documentos para separar antes",
     "Um guia simples para organizar a situação antes de qualquer consulta.",
     "Utilidade prática que atrai e qualifica quem precisa.",
     "Lista correta para a área de atuação.",
     "Cadastre-se", "Formulário que entrega o guia.",
     "Conteúdo informativo e discreto; sem convite comercial agressivo.", ["guia"]),
    ("Advocacia: o que muda com a nova regra", "editorial_manchete", "trafego",
     "Mudança de lei gera dúvida no público.",
     "Composição editorial própria: manchete serifada grande, linha fina, foto real de documento; identidade do escritório.",
     "O que muda com a nova regra",
     "Explicamos em 5 pontos, com a fonte da lei.",
     "Novidade real com entrega completa na página.",
     "Norma real citada com número e data.",
     "Saiba mais", "Artigo no site do escritório.",
     "Não imitar portal de notícias; sem sensacionalismo.", ["novidade"]),
    ("Advocacia: dúvida da semana", "objecao_na_manchete", "seguidores",
     "Dúvida jurídica frequente no dia a dia (aluguel, compra, trabalho).",
     "Pergunta grande entre aspas, resposta curta e informativa em cor, foto real da advogada.",
     "Posso cancelar e pedir reembolso?",
     "Toda semana respondemos uma dúvida comum no perfil.",
     "Dúvida real vira conteúdo informativo e autoridade.",
     "Resposta correta com base legal; inscrição na OAB.",
     "Saiba mais", "Perfil do Instagram.",
     "Informativo; sem prometer resultado; sem usar caso de cliente.", ["duvida"]),
    ("Advocacia: labirinto da burocracia", "metafora_visual", "reconhecimento",
     "Processo jurídico parece confuso e intimidador.",
     "Labirinto de papéis literal visto de cima, com um caminho marcado na cor da marca.",
     "Direito explicado sem juridiquês",
     "Conteúdo claro sobre direitos, com a fonte de cada informação.",
     "Metáfora da confusão resolvida por clareza.",
     "Canal com conteúdo real e frequente.",
     "Saiba mais", "Perfil do Instagram.",
     "Discrição exigida pela OAB; sem ostentação.", ["metafora"]),
]

P["imobiliaria"] = [
    ("Imobiliária: quanto custa morar aqui", "numero_em_destaque", "leads",
     "Comprador que só vê o preço total e não entende a parcela.",
     "Valor real da parcela em tamanho gigante na cor de destaque, rótulo com a condição, foto real da fachada no canto.",
     "Parcelas a partir de [valor real]",
     "Simulação com a condição completa da construtora. Receba a sua.",
     "Traduzir o preço em parcela reduz o esforço percebido.",
     "Condição real e completa da construtora, com data de validade.",
     "Cadastre-se", "Formulário com bairro de interesse e faixa de valor.",
     "Moradia pode exigir categoria especial; sem afirmar situação financeira; condição completa na copy.", ["preco", "financiamento"]),
    ("Imobiliária: perto do que importa", "local_e_bairro", "mensagens",
     "Família que quer morar perto do trabalho e da escola.",
     "Mapa estilizado com pino grande na cor da marca e distâncias reais em minutos até pontos conhecidos.",
     "Perto de tudo que importa no [bairro]",
     "Distâncias reais a pé e de carro. Chame para ver as unidades disponíveis.",
     "Localização concreta como benefício.",
     "Distâncias medidas; pontos de referência reais.",
     "Enviar mensagem", "WhatsApp.",
     "Distâncias reais; sem segmentar por atributo sensível.", ["localizacao"]),
    ("Imobiliária: acabamento de perto", "close_extremo", "agendamento",
     "Comprador desconfiado da qualidade do imóvel.",
     "Macro do acabamento real (piso, esquadria, metal) com luz lateral.",
     "Olhe o acabamento de perto",
     "Agende a visita e veja cada detalhe pessoalmente.",
     "Detalhe como prova de qualidade.",
     "Foto real do imóvel anunciado.",
     "Agendar", "Agenda de visitas.",
     "Foto real; nada de imagem de outro empreendimento.", ["qualidade"]),
    ("Imobiliária: checklist da visita", "lista_checklist", "seguidores",
     "Comprador de primeira viagem sem saber o que olhar na visita.",
     "Lista de 5 itens com checks grandes e uma prancheta real.",
     "5 coisas para olhar na visita",
     "Toda semana uma dica para comprar sem erro no nosso perfil.",
     "Utilidade gera autoridade e seguidores qualificados.",
     "Dicas corretas; CRECI do responsável.",
     "Saiba mais", "Perfil do Instagram.",
     "Baixo; sem promessa de valorização.", ["dica"]),
    ("Imobiliária: o apartamento como ele é", "ugc_nativo", "trafego",
     "Comprador cansado de foto que não bate com o imóvel.",
     "Foto de celular do corretor real dentro do apartamento, luz natural, legenda nativa curta.",
     "Sem filtro: o apartamento como é",
     "Veja o tour completo com todas as fotos reais.",
     "Autenticidade combate a desconfiança.",
     "Fotos reais sem edição enganosa.",
     "Saiba mais", "Página do imóvel.",
     "Sem imitar interface; foto do imóvel real.", ["autenticidade"]),
]

P["restaurante_delivery"] = [
    ("Delivery: prato no auge em close", "close_extremo", "vendas",
     "Fome no fim da tarde, decidindo o jantar.",
     "Macro do prato real no auge (queijo puxando, vapor, crocância), cores quentes e naturais.",
     "Sai do forno direto para você",
     "Peça pelo app ou WhatsApp. Entrega em [bairros reais].",
     "Desejo sensorial imediato.",
     "Foto real do prato do restaurante.",
     "Ver menu", "Cardápio no app de delivery ou WhatsApp.",
     "Foto real, sem banco de imagem.", ["desejo"]),
    ("Delivery: combo da sexta", "oferta_direta", "vendas",
     "Família decidindo o que pedir na sexta.",
     "Combo real fotografado de cima, preço real gigante, selo com o que vem no combo.",
     "Combo família por [preço real]",
     "Válido [dias reais]. Peça até [horário real].",
     "Oferta clara com condição real.",
     "Preço e condição confirmados pelo restaurante.",
     "Comprar agora", "App de delivery ou WhatsApp.",
     "Promoção só com dia e condição reais.", ["combo", "oferta"]),
    ("Delivery: feito agora na cozinha", "bastidor_real", "seguidores",
     "Cliente desconfia de comida requentada.",
     "Cozinheiro real montando o prato, mãos e fogo em foco, foto viva.",
     "Feito na hora, não requentado",
     "Mostramos a cozinha todo dia no perfil.",
     "Bastidor como prova de frescor.",
     "Foto real da cozinha em funcionamento.",
     "Saiba mais", "Perfil do Instagram.",
     "Baixo; cozinha real e limpa.", ["bastidor"]),
    ("Delivery: entregamos no seu bairro", "local_e_bairro", "mensagens",
     "Morador que acha que o restaurante não entrega na região dele.",
     "Mapa estilizado com a área de entrega na cor da marca e o prato no centro.",
     "Entregamos no [bairro], chega quente",
     "Tempo médio real de [minutos reais]. Chame e peça.",
     "Remover a objeção de cobertura.",
     "Área e tempo de entrega reais.",
     "Enviar mensagem", "WhatsApp.",
     "Tempo de entrega real.", ["cobertura"]),
    ("Delivery: meio a meio acaba a briga", "humor_situacao", "reconhecimento",
     "Família discutindo o sabor da pizza.",
     "Ilustração própria: pizza dividida em sabores com bandeirinhas de cada pessoa da casa.",
     "Meio a meio acaba com a discussão",
     "Monte a pizza meio a meio do jeito da família.",
     "Humor com situação cotidiana.",
     "Opção meio a meio existe no cardápio.",
     "Ver menu", "Cardápio.",
     "Rir da situação, nunca de pessoas.", ["humor"]),
]

P["academia"] = [
    ("Academia: treino que cabe no almoço", "tipografia_gigante", "agendamento",
     "Trabalhador sem tempo que acha que treinar exige horas.",
     "Frase gigante com a duração em destaque, relógio real quebrando a grade, fundo chapado da marca.",
     "Treino que cabe no seu almoço",
     "Treino guiado de [duração real]. Agende uma aula experimental.",
     "Remover a objeção de tempo com número real.",
     "Duração real do treino; aula experimental real.",
     "Agendar", "WhatsApp ou agenda.",
     "Sem promessa de corpo; falar para quem quer, nunca de quem é.", ["tempo"]),
    ("Academia: primeira semana acompanhada", "oferta_direta", "leads",
     "Quem quer voltar a treinar e tem receio de se perder na academia.",
     "Oferta grande com a semana acompanhada, selo com a condição real, foto real do professor com aluno.",
     "Primeira semana com professor ao lado",
     "Para quem quer voltar a treinar com segurança. Condição válida até [data real].",
     "Reverter risco e esforço com acompanhamento.",
     "Acompanhamento real; CREF do professor.",
     "Cadastre-se", "Formulário instantâneo.",
     "Sem atributo pessoal; sem antes e depois de corpo.", ["oferta"]),
    ("Academia: existe academia sem fila", "humor_situacao", "mensagens",
     "Pessoa que odeia fila de aparelho.",
     "Foto encenada própria: aparelho vazio com plaquinha de reservado, luz clara e cores da marca.",
     "Sim, existe academia sem fila",
     "Veja os horários mais tranquilos e chame para conhecer.",
     "Humor com dor de contexto (fila).",
     "Horários de menor movimento reais.",
     "Enviar mensagem", "WhatsApp.",
     "Sem ridicularizar corpos.", ["humor"]),
    ("Academia: gente de verdade treinando", "ugc_nativo", "seguidores",
     "Iniciante intimidado por academia que parece só de atleta.",
     "Foto de celular de aluno real autorizado treinando, legenda nativa curta.",
     "Treino de verdade, gente de verdade",
     "Acompanhe o dia a dia da academia no perfil.",
     "Pertencimento e autenticidade.",
     "Aluno real com autorização de imagem.",
     "Saiba mais", "Perfil do Instagram.",
     "Sem foco em corpo; autorização por escrito.", ["pertencimento"]),
    ("Academia: perto de casa", "local_e_bairro", "reconhecimento",
     "Morador que não sabe que tem academia perto.",
     "Fachada real grande, pino da marca e nome do bairro na manchete.",
     "Treine perto de casa no [bairro]",
     "Estrutura completa e horário estendido. Venha conhecer.",
     "Conveniência local.",
     "Fachada e horários reais.",
     "Saiba mais", "Perfil ou página com endereço.",
     "Baixo.", ["local"]),
]

P["moda"] = [
    ("Moda: peça herói em cor chapada", "produto_heroi_cor", "vendas",
     "Cliente rolando o feed sem intenção de compra.",
     "Peça real recortada em ângulo dinâmico sobre fundo saturado complementar, selo com benefício real.",
     "A peça que vira três looks",
     "Veja as combinações na loja. Troca fácil em [prazo real].",
     "Produto herói com benefício de versatilidade.",
     "Fotos reais; política de troca real.",
     "Comprar agora", "Página do produto.",
     "Sem corpo idealizado ou foco em parte do corpo.", ["produto"]),
    ("Moda: costura de perto", "close_extremo", "vendas",
     "Cliente com medo de qualidade ruim em loja online.",
     "Macro do tecido e da costura real, luz lateral.",
     "Olhe a costura antes de comprar",
     "Tecido [composição real]. Veja os detalhes na página.",
     "Detalhe como prova de qualidade.",
     "Composição real do tecido; foto real.",
     "Comprar agora", "Página do produto.",
     "Baixo.", ["qualidade"]),
    ("Moda: a mesma peça em gente de verdade", "ugc_nativo", "seguidores",
     "Cliente não sabe como a peça veste em corpos diferentes.",
     "Grade de fotos de celular de clientes reais autorizados vestindo a mesma peça.",
     "A mesma peça em gente de verdade",
     "Mande sua foto e apareça no perfil.",
     "Prova social visual e diversidade real.",
     "Fotos autorizadas de clientes reais.",
     "Saiba mais", "Perfil do Instagram.",
     "Autorização de imagem; sem foco negativo em corpo.", ["prova_social"]),
    ("Moda: look completo em kit", "pilha_de_oferta", "vendas",
     "Cliente com evento e sem saber montar o look.",
     "Look inteiro em flat lay (peça, acessório, sapato) com rótulos e o preço real do kit.",
     "Look completo pronto para o evento",
     "Kit por [preço real]. Itens separados somam [soma real].",
     "Pacote reduz o esforço de decidir.",
     "Preços reais praticados item a item.",
     "Comprar agora", "Página do kit.",
     "Ancoragem só com preço real.", ["kit"]),
    ("Moda: 3 jeitos de usar", "lista_checklist", "trafego",
     "Quem compra e não sabe combinar.",
     "Lista com 3 combinações ilustradas por fotos reais pequenas e checks na cor da marca.",
     "3 jeitos de usar a mesma camisa",
     "Veja o guia completo na loja.",
     "Utilidade que vende.",
     "Fotos reais das combinações.",
     "Saiba mais", "Página da loja com o guia.",
     "Baixo.", ["guia"]),
]

P["pet"] = [
    ("Pet: banho sem estresse", "bastidor_real", "agendamento",
     "Tutor com receio de que o pet se estresse no banho.",
     "Foto real do pet sendo secado com calma, mãos da tosadora, ambiente claro.",
     "Banho sem estresse, veja como é",
     "Agende e acompanhe como foi o atendimento.",
     "Bastidor responde ao medo do tutor.",
     "Fotos reais com autorização do tutor.",
     "Agendar", "WhatsApp.",
     "Sem animal sofrendo ou em situação de risco.", ["bastidor"]),
    ("Pet: buscamos e devolvemos", "demonstracao_etapas", "mensagens",
     "Tutor sem tempo de levar o pet.",
     "Três quadros numerados: buscamos, cuidamos, devolvemos; carro real da empresa.",
     "Buscamos, cuidamos e devolvemos no dia",
     "Atendemos [bairros reais]. Chame e agende.",
     "Conveniência demonstrada em etapas.",
     "Serviço real de leva e traz.",
     "Enviar mensagem", "WhatsApp.",
     "Baixo.", ["conveniencia"]),
    ("Pet: o olhar que pede banho", "rosto_e_olhar", "reconhecimento",
     "Tutor apaixonado pelo pet.",
     "Close do pet real olhando para a manchete, fundo chapado da marca.",
     "Ele merece o melhor dia da semana",
     "Banho, tosa e carinho no [bairro].",
     "Emoção e olhar direcionando a leitura.",
     "Pet real com autorização do tutor.",
     "Saiba mais", "Perfil do Instagram.",
     "Baixo.", ["emocao"]),
    ("Pet: a ração acabou de novo", "humor_situacao", "vendas",
     "Tutor que esquece de comprar ração.",
     "Foto encenada própria: pote vazio e o pet olhando com cara de indignado.",
     "A ração acaba antes de você lembrar",
     "Entrega de ração em [prazo real] na região.",
     "Humor com dor de contexto.",
     "Entrega real no prazo informado.",
     "Comprar agora", "WhatsApp ou loja.",
     "Sem animal em sofrimento.", ["humor", "recorrencia"]),
    ("Pet: pet shop do bairro", "local_e_bairro", "seguidores",
     "Morador com pet que não conhece o pet shop da região.",
     "Fachada real com mapa estilizado e pino na cor da marca.",
     "O pet shop do [bairro]",
     "Siga para ver os atendimentos do dia e as novidades.",
     "Conveniência local e rotina visível.",
     "Fachada real e endereço.",
     "Saiba mais", "Perfil do Instagram.",
     "Baixo.", ["local"]),
]

P["automotivo_oficina"] = [
    ("Oficina: orçamento com foto da peça", "close_extremo", "mensagens",
     "Motorista com medo de ser enganado no orçamento.",
     "Close da peça gasta real ao lado da nova, na mão do mecânico.",
     "Você vê a peça que trocamos",
     "Orçamento com foto e explicação antes de qualquer serviço.",
     "Transparência como prova.",
     "Processo real de orçamento com foto.",
     "Solicitar orçamento", "WhatsApp.",
     "Sem susto falso de segurança.", ["transparencia"]),
    ("Oficina: barulho na subida", "objecao_na_manchete", "agendamento",
     "Motorista ouve um barulho e adia a ida à oficina.",
     "Pergunta grande entre aspas e resposta com o diagnóstico em bloco de cor; foto real da oficina.",
     "Aquele barulho na subida tem nome",
     "Diagnóstico em [tempo real] com explicação do que é e do que não é urgente.",
     "Situação reconhecível vira pauta.",
     "Diagnóstico real oferecido.",
     "Agendar", "WhatsApp.",
     "Sem medo exagerado nem urgência falsa.", ["situacao"]),
    ("Oficina: o que sua revisão inclui", "comparacao_lado_a_lado", "leads",
     "Motorista comparando revisões só pelo preço.",
     "Quadro dividido: revisão básica comum com poucos itens e a revisão da oficina com a lista real; mesmo layout, cor da marca do lado da oficina.",
     "Compare o que sua revisão inclui",
     "Lista completa dos itens verificados. Receba a sua.",
     "Comparação justa por critério verificável (itens).",
     "Checklist real da revisão.",
     "Cadastre-se", "Formulário instantâneo com modelo do carro.",
     "Sem nomear concessionária ou concorrente.", ["comparacao"]),
    ("Oficina: funilaria antes e depois", "antes_depois", "mensagens",
     "Dono de carro com amassado adiando o conserto.",
     "Duas fotos do mesmo carro, mesmo ângulo e mesma luz, rótulos grandes.",
     "Mesmo carro, outro acabamento",
     "Orçamento pela foto no WhatsApp.",
     "Transformação visível e verificável.",
     "Fotos reais de serviço próprio com autorização do dono.",
     "Enviar mensagem", "WhatsApp.",
     "Fora de saúde e corpo: permitido; sem piorar o antes.", ["transformacao"]),
    ("Oficina: pronto no dia combinado", "demonstracao_etapas", "seguidores",
     "Motorista que já ficou dias sem carro.",
     "Três quadros: entrada com checklist, serviço com foto, entrega no horário.",
     "Seu carro pronto no dia combinado",
     "Siga e veja como cada carro passa pela oficina.",
     "Processo previsível como diferencial.",
     "Prazo real cumprido; fotos reais.",
     "Saiba mais", "Perfil do Instagram.",
     "Prazo só se cumprido de fato.", ["prazo"]),
]

P["cursos_infoproduto"] = [
    ("Curso: aula curta que se aplica hoje", "tipografia_gigante", "vendas",
     "Profissional sem tempo que já abandonou curso longo.",
     "Frase gigante com a duração real das aulas em destaque, fundo chapado, fone ou caderno real quebrando a grade.",
     "Aula curta que você aplica hoje",
     "Aulas de [duração real] com exercício no final. Garantia de [prazo real].",
     "Remover a objeção de tempo e de aplicação.",
     "Duração real das aulas; garantia real.",
     "Comprar agora", "Página de vendas.",
     "Sem promessa de ganho ou renda.", ["tempo"]),
    ("Curso: tudo que vem no curso", "pilha_de_oferta", "vendas",
     "Público quente comparando cursos.",
     "Pilha organizada com módulos, materiais, suporte e certificado em cartões, selo da garantia real.",
     "Tudo que vem no curso",
     "Módulos, materiais, suporte e certificado. Garantia de [prazo real].",
     "Entregáveis visíveis aumentam o valor percebido.",
     "Ementa real; garantia real.",
     "Comprar agora", "Página de vendas.",
     "Ancoragem só com valores reais; sem promessa de renda.", ["entregaveis"]),
    ("Curso: o freio de quem começa", "objeto_inesperado", "leads",
     "Iniciante que estuda muito e não avança.",
     "Freio de mão de carro real sobre uma mesa de estudo com caderno, fundo limpo.",
     "O erro que trava quem começa",
     "Aula gratuita mostra o erro e como sair dele.",
     "Objeto fora do lugar representa o bloqueio.",
     "Aula gratuita realmente disponível.",
     "Cadastre-se", "Página ou formulário da aula gratuita.",
     "Sem promessa de resultado financeiro.", ["isca", "incongruencia"]),
    ("Curso: assista a primeira aula", "rosto_e_olhar", "trafego",
     "Comprador desconfiado da qualidade do conteúdo.",
     "Professor real apontando para o selo da aula liberada, fundo sólido da marca.",
     "Assista a primeira aula antes de comprar",
     "A aula 1 está liberada na página. Veja se é para você.",
     "Amostra real reduz o risco percebido.",
     "Aula realmente liberada.",
     "Saiba mais", "Página com a aula.",
     "Sem promessa de renda.", ["amostra"]),
    ("Curso: o que se aprende no módulo 1", "lista_checklist", "leads",
     "Interessado que não sabe se o curso é prático.",
     "Checklist com 4 entregas do módulo 1 e print real da plataforma pequeno no canto (sem simular interface clicável).",
     "O que você aprende no módulo 1",
     "Receba a ementa completa e a data da próxima turma.",
     "Entregáveis concretos como prova de praticidade.",
     "Ementa real.",
     "Cadastre-se", "Formulário.",
     "Print só da plataforma real, sem botões falsos.", ["ementa"]),
]

P["saude_clinica"] = [
    ("Clínica: consulta com tempo para perguntar", "objecao_na_manchete", "agendamento",
     "Paciente cansado de consulta corrida.",
     "Pergunta do paciente entre aspas em letras grandes, resposta em cor; foto real do consultório.",
     "Consulta com tempo para perguntar",
     "Consultas de [duração real] com explicação do plano de cuidado.",
     "Objeção de atendimento corrido respondida com o formato real.",
     "Duração real da consulta; registro do profissional.",
     "Agendar", "Agenda online ou WhatsApp.",
     "Sem promessa de cura; sem atributo de saúde de quem vê.", ["objecao"]),
    ("Clínica: quem procurar primeiro", "lista_checklist", "trafego",
     "Pessoa com uma queixa comum sem saber qual especialista procurar.",
     "Lista com 3 sinais de quando procurar cada especialista, ícones grandes e foto real da equipe.",
     "Dor nas costas: quem procurar primeiro",
     "Um guia simples, escrito pela equipe da clínica.",
     "Informação útil que posiciona a clínica.",
     "Conteúdo revisado pelo profissional responsável.",
     "Saiba mais", "Artigo no site.",
     "Falar do tema, nunca afirmar que a pessoa tem a condição; sem promessa.", ["informativo"]),
    ("Clínica: como é a primeira consulta", "demonstracao_etapas", "mensagens",
     "Paciente ansioso com a primeira consulta.",
     "Três quadros: recepção, conversa com o profissional, plano explicado.",
     "Como é a primeira consulta aqui",
     "Tire suas dúvidas antes de marcar.",
     "Demonstração reduz a ansiedade do desconhecido.",
     "Processo real de atendimento.",
     "Enviar mensagem", "WhatsApp.",
     "Sem promessa de resultado.", ["processo"]),
    ("Clínica: escuta de verdade", "rosto_e_olhar", "reconhecimento",
     "Público que procura atendimento psicológico e quer se sentir ouvido.",
     "Profissional real em close médio, expressão acolhedora, olhar para a manchete, fundo claro.",
     "Atendimento para ansiedade, com escuta de verdade",
     "Psicoterapia com [abordagem real]. Conheça como funciona.",
     "Confiança pela pessoa real e pelo tema do serviço, sem rotular quem vê.",
     "Registro no conselho; foto real autorizada.",
     "Saiba mais", "Perfil ou página.",
     "Dizer o serviço, nunca 'você tem ansiedade?'.", ["confianca"]),
    ("Clínica: horários esta semana", "local_e_bairro", "agendamento",
     "Paciente que precisa de horário rápido e perto.",
     "Fachada real e mapa com pino na cor da marca; selo com os dias com horário.",
     "Horários esta semana no [bairro]",
     "Consulte os horários disponíveis e marque pelo WhatsApp.",
     "Conveniência e rapidez reais.",
     "Agenda com horários realmente livres.",
     "Agendar", "WhatsApp.",
     "Escassez de horário só se real.", ["local", "agenda"]),
]

P["paisagismo_jardim"] = [
    ("Jardim: mesmo quintal, outro jardim", "antes_depois", "mensagens",
     "Dono de casa com quintal sem uso.",
     "Mesmo quintal em duas fotos com mesmo ângulo e mesma luz, rótulos grandes.",
     "Mesmo quintal, outro jardim",
     "Mande uma foto do seu espaço e receba uma ideia de projeto.",
     "Transformação visível e verificável.",
     "Fotos reais de projeto próprio com autorização do cliente.",
     "Enviar mensagem", "WhatsApp.",
     "Fora de saúde: permitido; foto real, sem piorar o antes.", ["transformacao"]),
    ("Jardim: regar todo dia não salva", "objeto_inesperado", "leads",
     "Dono de casa que rega todo dia e vê a planta morrer.",
     "Mangueira real dando um nó apertado sobre grama, fundo limpo.",
     "Regar todo dia não salva jardim",
     "Guia rápido de rega por tipo de planta. Receba grátis.",
     "Objeto inesperado ilustra o erro comum.",
     "Guia real com orientação correta.",
     "Cadastre-se", "Formulário que entrega o guia.",
     "Baixo.", ["contraintuitivo", "isca"]),
    ("Jardim: grama assim não é sorte", "close_extremo", "reconhecimento",
     "Vizinho que admira jardim bonito e acha que é sorte.",
     "Macro da grama real com gotas e luz de fim de tarde, cores vivas.",
     "Grama assim não é sorte",
     "É projeto, planta certa e manutenção. Conheça o trabalho.",
     "Detalhe como prova e afirmação contraintuitiva.",
     "Foto real de jardim mantido pela empresa.",
     "Saiba mais", "Perfil do Instagram.",
     "Baixo.", ["detalhe"]),
    ("Jardim: veja o projeto antes", "demonstracao_etapas", "agendamento",
     "Cliente com medo de gastar e não gostar do resultado.",
     "Três quadros: visita, projeto em 3D real, jardim pronto.",
     "Veja o projeto antes de plantar",
     "Visita técnica e projeto antes de qualquer plantio.",
     "Demonstração que reduz o risco percebido.",
     "Projeto 3D real e jardim executado real.",
     "Agendar", "WhatsApp.",
     "Prazo de crescimento depende do clima: não prometer.", ["processo"]),
    ("Jardim: você descansa, a gente cuida", "metafora_visual", "leads",
     "Dono de casa sem tempo para manter o jardim.",
     "Cadeira de descanso vazia no jardim bem cuidado e uma prancheta com o cronograma de manutenção pendurada.",
     "Você descansa, a gente cuida do jardim",
     "Manutenção mensal com visita programada. Peça sua proposta.",
     "Metáfora do descanso tira o esforço da oferta.",
     "Plano de manutenção real.",
     "Solicitar orçamento", "Formulário instantâneo.",
     "Baixo.", ["manutencao"]),
    ("Jardim: plantas para sombra", "lista_checklist", "seguidores",
     "Quem tem área com pouca luz e não sabe o que plantar.",
     "Lista de 5 plantas com fotos reais pequenas e checks na cor da marca.",
     "5 plantas que gostam de sombra",
     "Siga para mais dicas de jardim para cada espaço.",
     "Utilidade gera seguidores qualificados.",
     "Informação botânica correta.",
     "Saiba mais", "Perfil do Instagram.",
     "Baixo.", ["dica"]),
]

P["informatica_assistencia"] = [
    ("Assistência: diagnóstico antes da troca", "objecao_na_manchete", "mensagens",
     "Dono de computador lento que acha que precisa trocar de máquina.",
     "Pergunta grande entre aspas, resposta em bloco de cor, foto real da bancada.",
     "Precisa mesmo trocar? Diagnóstico primeiro",
     "Avaliamos e explicamos antes de você gastar.",
     "Objeção de custo respondida com diagnóstico.",
     "Diagnóstico real oferecido.",
     "Enviar mensagem", "WhatsApp.",
     "Sem imitar alerta de sistema; sem susto.", ["objecao"]),
    ("Assistência: bancada real", "bastidor_real", "seguidores",
     "Cliente desconfiado de onde o aparelho vai ficar.",
     "Foto real da bancada limpa, técnico trabalhando com pulseira antiestática, luz clara.",
     "Assim cuidamos do seu computador",
     "Siga e veja os consertos do dia.",
     "Bastidor como prova de cuidado.",
     "Fotos reais da bancada.",
     "Saiba mais", "Perfil do Instagram.",
     "Baixo.", ["bastidor"]),
    ("Assistência: lento não é normal", "objeto_inesperado", "leads",
     "Profissional que perde tempo com computador lento.",
     "Tartaruga de brinquedo parada sobre o teclado de um notebook real, fundo limpo.",
     "Lento não é normal",
     "Peça uma avaliação e descubra o motivo da lentidão.",
     "Objeto inesperado representa a lentidão sem imitar tela de erro.",
     "Avaliação real.",
     "Solicitar orçamento", "Formulário instantâneo.",
     "Proibido imitar janela de erro, aviso de vírus ou notificação.", ["incongruencia"]),
    ("Assistência: seus arquivos saem com você", "close_extremo", "agendamento",
     "Cliente com medo de perder arquivos no conserto.",
     "Close da unidade de armazenamento real na mão do técnico, foco cravado.",
     "Seus arquivos saem com você",
     "Backup antes de qualquer serviço, se você autorizar.",
     "Detalhe físico torna a segurança dos dados concreta.",
     "Procedimento real de backup.",
     "Agendar", "WhatsApp.",
     "Sem garantir recuperação que não pode prometer.", ["seguranca"]),
    ("Assistência: conserto no bairro", "local_e_bairro", "reconhecimento",
     "Morador que não conhece assistência técnica perto.",
     "Fachada real com mapa estilizado e pino na cor da marca.",
     "Conserto no [bairro] com prazo combinado",
     "Orçamento sem compromisso, se for verdade, e prazo combinado.",
     "Conveniência local.",
     "Endereço e política de orçamento reais.",
     "Saiba mais", "Perfil ou Google Maps.",
     "Baixo.", ["local"]),
]

P["ecommerce_geral"] = [
    ("E-commerce: o mais vendido em cor chapada", "produto_heroi_cor", "vendas",
     "Comprador rolando o feed sem intenção.",
     "Produto real recortado e grande em ângulo heroico sobre cor saturada complementar, selo de mais vendido só se for real.",
     "O mais vendido da loja tem motivo",
     "Veja por que é o preferido e escolha o seu.",
     "Produto herói e prova de popularidade real.",
     "Dado real de vendas da loja.",
     "Comprar agora", "Página do produto.",
     "Selo só com dado real.", ["produto"]),
    ("E-commerce: frete grátis acima de", "oferta_direta", "vendas",
     "Comprador que abandona o carrinho por causa do frete.",
     "Condição de frete em letras gigantes, produto real ao lado, selo com o prazo real.",
     "Frete grátis acima de [valor real]",
     "Válido até [data real] para [regiões reais].",
     "Remover o atrito do frete com condição clara.",
     "Condição real e completa.",
     "Comprar agora", "Loja.",
     "Condição completa; sem prazo falso.", ["frete", "oferta"]),
    ("E-commerce: palavra de quem comprou", "depoimento_citacao", "vendas",
     "Comprador com medo de golpe ou de produto diferente da foto.",
     "Aspas gigantes, trecho real de avaliação autorizada, iniciais e cidade, foto real do produto.",
     "Palavras de quem já comprou",
     "Mais avaliações reais na página do produto.",
     "Prova social real antes da explicação.",
     "Avaliação real e autorizada, com fonte.",
     "Comprar agora", "Página do produto.",
     "Nunca escrever depoimento; estrelas só de avaliação real.", ["prova_social"]),
    ("E-commerce: comparação de material", "comparacao_lado_a_lado", "vendas",
     "Comprador comparando o produto com opções mais baratas.",
     "Quadro dividido: material comum e material do produto, mesmo enquadramento e luz, rótulos curtos.",
     "Mesmo uso, material diferente",
     "Veja a composição e as medidas na página.",
     "Comparação justa por critério verificável.",
     "Especificação real do material.",
     "Comprar agora", "Página do produto.",
     "Sem nomear ou mostrar marca concorrente.", ["comparacao"]),
    ("E-commerce: kit com bônus", "pilha_de_oferta", "vendas",
     "Comprador quente indeciso entre um e outro produto.",
     "Kit organizado em pilha com o bônus real destacado por selo na cor da marca.",
     "Leve o kit e ganhe [bônus real]",
     "Kit por [preço real] até [data real].",
     "Bônus que resolve o próximo problema do comprador.",
     "Bônus e preço reais.",
     "Obter oferta", "Página do kit.",
     "Ancoragem só com preço real.", ["kit", "bonus"]),
    ("E-commerce: chegou assim, sem filtro", "ugc_nativo", "reconhecimento",
     "Público frio que ignora anúncio com cara de anúncio.",
     "Foto de celular de cliente real abrindo a caixa, luz natural, legenda nativa curta.",
     "Chegou assim, sem filtro",
     "Embalagem e produto como o cliente recebe.",
     "Autenticidade e prova de entrega.",
     "Foto real autorizada de cliente.",
     "Saiba mais", "Perfil ou loja.",
     "Sem imitar interface; autorização.", ["autenticidade"]),
]

P["eventos_festas"] = [
    ("Festas: tudo incluso sem surpresa", "pilha_de_oferta", "leads",
     "Família planejando festa com medo de orçamento que cresce.",
     "Todos os itens do pacote fotografados em grade organizada, cada um com rótulo, selo do valor real do pacote.",
     "Tudo incluso, sem surpresa no final",
     "Receba o pacote completo com o que está incluso.",
     "Entregáveis visíveis e previsibilidade.",
     "Lista real do pacote.",
     "Solicitar orçamento", "Formulário instantâneo com data e número de convidados.",
     "Valores só reais; sem escassez falsa.", ["pacote"]),
    ("Festas: festa montada de verdade", "bastidor_real", "seguidores",
     "Cliente que não consegue imaginar como vai ficar.",
     "Foto real da montagem no dia, equipe ajustando a decoração, luz do salão.",
     "Veja uma festa montada de verdade",
     "Siga para ver as montagens da semana.",
     "Bastidor como prova do resultado.",
     "Fotos reais de eventos próprios.",
     "Saiba mais", "Perfil do Instagram.",
     "Autorização dos contratantes para as fotos.", ["bastidor"]),
    ("Festas: a data ainda está livre", "oferta_direta", "mensagens",
     "Cliente com data definida que ainda não consultou disponibilidade.",
     "Pergunta gigante sobre a data, calendário real com a data marcada na cor da marca.",
     "Sua data ainda está livre?",
     "Consulte a agenda e reserve com [condição real].",
     "Escassez real de datas como motivo para agir.",
     "Agenda real de datas.",
     "Enviar mensagem", "WhatsApp com a data como primeira mensagem.",
     "Escassez só se a agenda estiver de fato concorrida.", ["agenda"]),
    ("Festas: o que não pode faltar", "lista_checklist", "leads",
     "Primeira vez organizando festa.",
     "Checklist de 5 itens com checks grandes, foto real de mesa posta.",
     "O que não pode faltar na festa",
     "Baixe o checklist completo para organizar sem esquecer nada.",
     "Utilidade que qualifica quem está organizando.",
     "Checklist real e útil.",
     "Cadastre-se", "Formulário que entrega o checklist.",
     "Baixo.", ["isca"]),
    ("Festas: detalhe que vira foto", "close_extremo", "reconhecimento",
     "Convidado e anfitrião que valorizam o detalhe.",
     "Macro de um doce ou arranjo real da mesa, cores vivas.",
     "Detalhe que os convidados fotografam",
     "Conheça o nosso trabalho de perto.",
     "Detalhe como prova de capricho.",
     "Foto real de evento próprio.",
     "Saiba mais", "Perfil do Instagram.",
     "Baixo.", ["detalhe"]),
]

P["b2b_servicos"] = [
    ("B2B: compare antes de assinar", "nos_contra_eles", "leads",
     "Gestor comparando fornecedores só pelo preço.",
     "Tabela grande com 5 linhas, check na coluna da empresa e x na coluna do jeito comum, coluna da empresa em cor de destaque.",
     "Compare antes de assinar",
     "Receba o comparativo do que está incluso no nosso serviço.",
     "Comparação justa por critérios objetivos.",
     "Diferenciais reais e verificáveis.",
     "Solicitar orçamento", "Formulário com porte da empresa.",
     "Sem nomear concorrente; sem promessa de faturamento.", ["comparacao"]),
    ("B2B: depois do contrato", "demonstracao_etapas", "leads",
     "Empresa que já foi abandonada por fornecedor depois de fechar.",
     "Três quadros: reunião de início, entregas com responsável, relatório mensal.",
     "Depois do contrato, o que acontece?",
     "Veja nosso processo e quem cuida de cada etapa.",
     "Processo visível como prova de previsibilidade.",
     "Processo documentado real.",
     "Saiba mais", "Página do processo.",
     "Sem promessa de resultado financeiro.", ["processo"]),
    ("B2B: retrabalho em pilha", "metafora_visual", "trafego",
     "Equipe que refaz a mesma tarefa toda semana.",
     "Pilha literal de papéis iguais carimbados de novo, fundo limpo, carimbo na cor da marca.",
     "Retrabalho custa mais que parece",
     "Entenda onde o processo perde tempo.",
     "Metáfora concreta de desperdício.",
     "Conteúdo real na página.",
     "Saiba mais", "Artigo ou diagnóstico.",
     "Sem dado sem fonte.", ["metafora"]),
    ("B2B: guia do setor", "editorial_manchete", "leads",
     "Gestor que busca referência para decidir.",
     "Capa editorial própria com manchete serifada, linha fina e foto real do setor.",
     "Guia 2026 para [setor] com dados",
     "Material gratuito com fontes citadas.",
     "Curiosidade com entrega real.",
     "Guia real com fontes.",
     "Baixar", "Formulário que entrega o guia.",
     "Não imitar veículo de imprensa.", ["isca"]),
    ("B2B: número real de clientes", "numero_em_destaque", "leads",
     "Decisor que precisa de segurança para contratar.",
     "Número real em escala gigante, rótulo e período em letra menor, logos de clientes só autorizados.",
     "[número real] empresas atendidas desde [ano]",
     "Conheça casos com autorização dos clientes.",
     "Prova numérica real com período.",
     "Número real com período e fonte.",
     "Saiba mais", "Página de casos.",
     "Logos só com autorização.", ["prova"]),
]

P["games_keys"] = [
    ("Games: comprou, recebeu, ativou", "demonstracao_etapas", "vendas",
     "Gamer com medo de key que demora ou não chega.",
     "Três quadros: compra, e-mail com a key, jogo ativado; tela gravada real do processo.",
     "Comprou, recebeu, ativou em minutos",
     "Entrega em [tempo real] com suporte se a ativação falhar.",
     "Demonstração da entrega remove o medo de golpe.",
     "Tempo real de entrega; gravação real da ativação.",
     "Comprar agora", "Loja.",
     "Arte de jogo só com licença ou material oficial autorizado.", ["entrega"]),
    ("Games: mesmo jogo, preço diferente", "comparacao_lado_a_lado", "vendas",
     "Gamer que acha o preço oficial alto.",
     "Quadro dividido com o preço de referência real e o preço da loja, capa do jogo só com autorização.",
     "Mesmo jogo, preço de [valor real]",
     "Key oficial para [plataforma real]. Veja a região antes de comprar.",
     "Comparação justa de preço com referência real.",
     "Preço de referência real com data.",
     "Comprar agora", "Página do jogo.",
     "Referência de preço real; sem logo de loja oficial.", ["preco"]),
    ("Games: e se a key não ativar", "objecao_na_manchete", "vendas",
     "Comprador que já caiu em golpe de key.",
     "Pergunta gigante entre aspas, resposta com a garantia real em bloco de cor.",
     "E se a key não ativar?",
     "Suporte e [política real de troca ou reembolso].",
     "Objeção principal respondida com garantia real.",
     "Política real de garantia.",
     "Comprar agora", "Loja.",
     "Garantia só a que existe.", ["garantia"]),
    ("Games: lançamento sem preço cheio", "oferta_direta", "vendas",
     "Gamer esperando o lançamento.",
     "Preço real gigante, selo de key oficial, arte autorizada do jogo.",
     "Lançamento por [preço real], key oficial",
     "Pré-venda até [data real].",
     "Oferta direta com condição real no pico de interesse.",
     "Preço e data reais; arte autorizada.",
     "Comprar agora", "Página do jogo.",
     "Sem arte de terceiros sem licença.", ["lancamento"]),
    ("Games: palavra de quem já ativou", "depoimento_citacao", "vendas",
     "Comprador novo desconfiado da loja.",
     "Aspas gigantes com trecho real de avaliação autorizada e nota pública real.",
     "Palavra de quem já ativou",
     "Veja todas as avaliações na página.",
     "Prova social real.",
     "Avaliação real com fonte.",
     "Comprar agora", "Loja.",
     "Nunca escrever depoimento.", ["prova_social"]),
    ("Games: promoção toda semana", "tipografia_gigante", "seguidores",
     "Gamer que caça promoção.",
     "Frase gigante em cor saturada, controle real pequeno quebrando a grade.",
     "Promoção de jogo toda semana aqui",
     "Siga para ver as ofertas da semana primeiro.",
     "Promessa de conteúdo recorrente para seguir.",
     "Frequência real de promoções.",
     "Saiba mais", "Perfil do Instagram.",
     "Só se a frequência for real.", ["recorrencia"]),
]

P["beleza_salao"] = [
    ("Salão: cor que cuida do fio", "close_extremo", "agendamento",
     "Cliente com medo de química danificar o cabelo.",
     "Macro do fio real com brilho natural e cor viva.",
     "Cor que cuida do fio",
     "Avaliação do fio antes de qualquer química.",
     "Detalhe como prova de cuidado.",
     "Foto real de trabalho do salão.",
     "Agendar", "WhatsApp.",
     "Sem falar mal da aparência de quem vê.", ["detalhe"]),
    ("Salão: do jeito que mostrou na foto", "antes_depois", "agendamento",
     "Cliente que já saiu diferente do que pediu.",
     "Mesma cliente, mesmo ângulo e mesma luz, rótulos grandes, trabalho real autorizado.",
     "Do jeito que você mostrou na foto",
     "Conversa e avaliação antes de começar.",
     "Transformação cosmética real com processo.",
     "Fotos reais autorizadas.",
     "Agendar", "WhatsApp.",
     "Cosmético: sem expectativa irreal; sem foco negativo; autorização.", ["transformacao"]),
    ("Salão: saiu assim hoje", "ugc_nativo", "seguidores",
     "Público que acompanha tendências de cabelo.",
     "Foto de celular da cliente real no espelho do salão, legenda nativa curta.",
     "Saiu do salão assim hoje",
     "Siga para ver os trabalhos do dia.",
     "Autenticidade e frequência.",
     "Foto real autorizada.",
     "Saiba mais", "Perfil do Instagram.",
     "Autorização; sem imitar interface.", ["autenticidade"]),
    ("Salão: posso descolorir?", "objecao_na_manchete", "mensagens",
     "Cliente com medo de estragar o cabelo com descoloração.",
     "Pergunta gigante entre aspas, resposta em cor, foto real da avaliação do fio.",
     "Posso descolorir? A gente avalia antes",
     "Mande uma foto do seu cabelo e receba a orientação.",
     "Objeção respondida com processo.",
     "Avaliação real oferecida.",
     "Enviar mensagem", "WhatsApp.",
     "Sem garantir resultado; sem afirmar dano no cabelo de quem vê.", ["objecao"]),
    ("Salão: horário esta semana", "local_e_bairro", "reconhecimento",
     "Moradora da região que precisa de horário rápido.",
     "Fachada real e mapa estilizado com pino, selo com os dias com horário.",
     "Horário esta semana no [bairro]",
     "Consulte os horários e marque pelo WhatsApp.",
     "Conveniência local.",
     "Agenda real.",
     "Saiba mais", "Perfil ou WhatsApp.",
     "Escassez de horário só se real.", ["local"]),
]

P["construcao_reforma"] = [
    ("Reforma: mesma cozinha, outra vida", "antes_depois", "mensagens",
     "Dono de imóvel adiando a reforma.",
     "Mesma cozinha em duas fotos com mesma perspectiva e mesma luz, rótulos grandes.",
     "Mesma cozinha, outra vida",
     "Mande fotos do seu ambiente e receba uma primeira avaliação.",
     "Transformação visível e verificável.",
     "Fotos reais de obra própria com autorização.",
     "Enviar mensagem", "WhatsApp.",
     "Fora de saúde: permitido; foto real.", ["transformacao"]),
    ("Reforma: orçamento fechado antes de quebrar", "comparacao_lado_a_lado", "leads",
     "Cliente com medo de orçamento que dobra no meio da obra.",
     "Quadro dividido: orçamento aberto com pontos de interrogação e orçamento fechado com itens e cronograma, cor da marca do lado da empresa.",
     "Orçamento fechado antes de quebrar",
     "Escopo, prazo e valor definidos antes de começar.",
     "Comparação justa de processos.",
     "Modelo real de orçamento fechado.",
     "Solicitar orçamento", "Formulário instantâneo.",
     "Prazo só com cronograma real.", ["orcamento"]),
    ("Reforma: acabamento de perto", "close_extremo", "reconhecimento",
     "Cliente que valoriza acabamento.",
     "Macro de rejunte, canto ou encaixe perfeito, luz lateral.",
     "Acabamento que aparece de perto",
     "Conheça as obras entregues.",
     "Detalhe como prova de qualidade.",
     "Foto real de obra própria.",
     "Saiba mais", "Perfil do Instagram.",
     "Baixo.", ["detalhe"]),
    ("Reforma: obra acompanhada pelo celular", "demonstracao_etapas", "leads",
     "Cliente que não pode ir à obra todo dia.",
     "Três quadros: cronograma, fotos semanais, entrega; celular na mão com foto real da obra (sem simular interface).",
     "Acompanhe sua obra pelo celular",
     "Relatório com fotos toda semana.",
     "Processo visível como prova.",
     "Rotina real de relatório.",
     "Cadastre-se", "Formulário.",
     "Sem imitar interface de aplicativo.", ["processo"]),
    ("Reforma: obra entregue limpa", "bastidor_real", "seguidores",
     "Cliente com medo de sujeira e bagunça.",
     "Foto real da equipe limpando o ambiente no fim da obra.",
     "Obra entregue limpa, veja como",
     "Siga para ver as entregas.",
     "Bastidor como prova de cuidado.",
     "Fotos reais.",
     "Saiba mais", "Perfil do Instagram.",
     "Baixo.", ["bastidor"]),
]


def palavras(s):
    return len([w for w in s.replace("?", " ").replace(",", " ").split() if w])


itens = []
erros = []
titulos = set()
for nicho, lista in P.items():
    if nicho not in NICHOS:
        erros.append(f"nicho desconhecido {nicho}")
    if not (4 <= len(lista) <= 6):
        erros.append(f"{nicho}: {len(lista)} padrões")
    estilos_do_nicho = [p[1] for p in lista]
    if len(set(estilos_do_nicho)) != len(estilos_do_nicho):
        erros.append(f"{nicho}: estilo repetido")
    for (titulo, estilo, objetivo, situacao, gv, gverb, apoio, mec, prova, cta, destino, riscos, extras) in lista:
        if estilo not in ESTILOS:
            erros.append(f"estilo {estilo}")
        if objetivo not in OBJETIVOS:
            erros.append(f"objetivo {objetivo}")
        if cta not in CTAS:
            erros.append(f"cta {cta}")
        if palavras(gverb) > 7:
            erros.append(f"gancho longo: {gverb}")
        if titulo in titulos:
            erros.append(f"titulo repetido {titulo}")
        titulos.add(titulo)
        e = ESTILOS[estilo]
        ficha = {
            "nicho": nicho,
            "estilo_visual": estilo,
            "situacao": situacao,
            "gancho_visual": gv,
            "gancho_verbal": gverb,
            "texto_apoio": apoio,
            "mecanismo": mec,
            "tecnica": TECNICA[estilo],
            "prova_necessaria": prova,
            "cta": cta,
            "destino": destino,
            "objetivo": objetivo,
            "o_que_transportar": f"A relação que faz funcionar: {mec[0].lower() + mec[1:]} Execução no estilo {e['nome']}.",
            "o_que_substituir": SUBSTITUIR,
            "riscos_de_politica": f"Estilo com risco {e['risco']}. {riscos}",
            "limites": f"Padrão de estudo E0 da agência: sem veiculação e sem métrica, é hipótese de criativo, não anúncio validado. Só produzir se existir: {prova[0].lower() + prova[1:]}",
            "fonte": FONTE,
        }
        tags = [nicho, estilo, objetivo, "padrao"] + extras
        itens.append({"titulo": titulo, "nicho": nicho, "estilo_visual": estilo, "tags": tags, "ficha": ficha})

texto_total = json.dumps(itens, ensure_ascii=False)
for ch in ("\u2014", "\u2013"):
    if ch in texto_total:
        erros.append("travessão encontrado")
if erros:
    print("\n".join(erros))
    sys.exit(1)

out_json = os.path.join(RAIZ, "docs", "mesa-ads", "v2", "biblioteca-padroes.json")
os.makedirs(os.path.dirname(out_json), exist_ok=True)
with open(out_json, "w", encoding="utf-8", newline="\n") as f:
    json.dump(itens, f, ensure_ascii=False, indent=2)
    f.write("\n")


def q(s):
    return "'" + s.replace("'", "''") + "'"


linhas = []
for it in itens:
    tags = "ARRAY[" + ", ".join(q(t) for t in it["tags"]) + "]::text[]"
    ficha = q(json.dumps(it["ficha"], ensure_ascii=False)) + "::jsonb"
    linhas.append(f"  ({q(it['titulo'])}, {q(it['ficha']['mecanismo'])}, {tags}, {ficha})")

sql = f"""-- ═══════════════════════════════════════════════════════════════════════
-- MESA ADS v2: semente da biblioteca de padrões por nicho (frente D).
-- Gerado por script a partir de docs/mesa-ads/v2/biblioteca-padroes.json
-- ({len(itens)} padrões, {len(P)} nichos). Não editar à mão: regenerar.
--
-- Cada linha é um PADRÃO de estudo da agência (evidência E0): sem marca de
-- terceiro, sem prova inventada, sem métrica. client_id NULL (biblioteca da
-- agência), origem 'padrao', formato 'imagem', plataforma 'meta'.
--
-- Depende da migration da frente A que acrescenta 'padrao' ao check de
-- ads_referencias.origem; rodar DEPOIS dela.
-- Idempotente: cada padrão só entra se ainda não existe um com o mesmo
-- título, origem 'padrao' e client_id NULL. Rodar de novo não duplica.
-- ═══════════════════════════════════════════════════════════════════════

INSERT INTO public.ads_referencias (client_id, titulo, origem, evidencia, mecanismo, formato, plataforma, tags, ficha, destaque, ativa)
SELECT NULL, v.titulo, 'padrao', 'E0', v.mecanismo, 'imagem', 'meta', v.tags, v.ficha, false, true
FROM (VALUES
{",\n".join(linhas)}
) AS v (titulo, mecanismo, tags, ficha)
WHERE NOT EXISTS (
  SELECT 1 FROM public.ads_referencias r
  WHERE r.client_id IS NULL AND r.origem = 'padrao' AND r.titulo = v.titulo
);
"""
out_sql = os.path.join(RAIZ, "docs", "mesa-ads", "v2", "migrations", "seed_biblioteca_padroes.sql")
os.makedirs(os.path.dirname(out_sql), exist_ok=True)
with open(out_sql, "w", encoding="utf-8", newline="\n") as f:
    f.write(sql)

from collections import Counter
print("padroes", len(itens), "nichos", len(P))
print("por estilo", Counter(i["estilo_visual"] for i in itens))
print("por objetivo", Counter(i["ficha"]["objetivo"] for i in itens))
print("nichos sem padrao", set(NICHOS) - set(P))
