// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/health.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var health_default = defineTool({
  name: "health",
  title: "Health check",
  description: "Verifica se o MCP do Aceleriq OS est\xE1 online e retorna o usu\xE1rio autenticado.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    const authed = ctx.isAuthenticated();
    return {
      content: [{
        type: "text",
        text: authed ? `ok \u2014 autenticado como ${ctx.getUserEmail() ?? ctx.getUserId()}` : "ok \u2014 sem autentica\xE7\xE3o"
      }],
      structuredContent: {
        status: "ok",
        authenticated: authed,
        user_id: authed ? ctx.getUserId() : null,
        user_email: authed ? ctx.getUserEmail() : null,
        server: "aceleriq-os"
      }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/compat.ts
var TASK_STATUS_VALUES = [
  "backlog",
  "todo",
  "doing",
  "review",
  "approved",
  "blocked",
  "done"
];
function normalizeTaskStatus(status) {
  return status === "todo" || !status ? "backlog" : status;
}
function taskStatusFilter(status) {
  return status === "todo" || status === "backlog" ? ["backlog", "todo"] : [status];
}
function sanitizeProfileSearch(search) {
  return (search ?? "").trim().replace(/[,%()]/g, " ").replace(/\s+/g, " ").trim().slice(0, 100);
}

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anonKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return {
      content: [{ type: "text", text: "N\xE3o autenticado. Conecte-se via OAuth para usar esta ferramenta." }],
      isError: true
    };
  }
  return null;
}

// src/lib/mcp/tools/list-clients.ts
var list_clients_default = defineTool2({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lista clientes vis\xEDveis ao usu\xE1rio autenticado (RLS aplicado).",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de registros (padr\xE3o 50)."),
    search: z.string().optional().describe("Filtro por nome ou empresa.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const { data: clientRoles, error: rolesError } = await sb.from("user_roles").select("user_id").eq("role", "client").limit(1e3);
    if (rolesError) {
      return { content: [{ type: "text", text: rolesError.message }], isError: true };
    }
    const clientIds = [...new Set((clientRoles ?? []).map((row) => row.user_id))];
    if (clientIds.length === 0) {
      return {
        content: [{ type: "text", text: "0 clientes." }],
        structuredContent: { clients: [] }
      };
    }
    let q = sb.from("profiles").select("id, full_name, email, company_name, plan_status, plan_name, client_type, created_at").in("id", clientIds).is("deleted_at", null).limit(limit ?? 50).order("created_at", { ascending: false });
    const safeSearch = sanitizeProfileSearch(search);
    if (safeSearch) {
      q = q.or(
        `full_name.ilike.%${safeSearch}%,company_name.ilike.%${safeSearch}%,email.ilike.%${safeSearch}%`
      );
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const clients = (data ?? []).map((client) => ({
      ...client,
      status: client.plan_status
    }));
    return {
      content: [{ type: "text", text: `${clients.length} clientes.` }],
      structuredContent: { clients }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "Listar projetos",
  description: "Lista projetos vis\xEDveis ao usu\xE1rio autenticado (RLS aplicado).",
  inputSchema: {
    client_id: z2.string().uuid().optional().describe("Filtrar por cliente."),
    status: z2.string().optional().describe("Filtrar por status do projeto."),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, status, limit }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    let q = sb.from("projects").select("id, name, status, progress, client_id, created_at, updated_at").is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (client_id) q = q.eq("client_id", client_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} projetos.` }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool4({
  name: "list_tasks",
  title: "Listar tarefas",
  description: "Lista tarefas do Kanban vis\xEDveis ao usu\xE1rio autenticado (RLS aplicado).",
  inputSchema: {
    project_id: z3.string().uuid().optional(),
    status: z3.enum(TASK_STATUS_VALUES).optional(),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, status, limit }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    let q = sb.from("tasks").select("id, title, description, status, priority, due_date, project_id, assigned_to, created_at").is("deleted_at", null).order("created_at", { ascending: false }).limit(limit ?? 100);
    if (project_id) q = q.eq("project_id", project_id);
    if (status) {
      const statuses = taskStatusFilter(status);
      q = statuses.length === 1 ? q.eq("status", statuses[0]) : q.in("status", statuses);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} tarefas.` }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
var create_task_default = defineTool5({
  name: "create_task",
  title: "Criar tarefa",
  description: "Cria uma nova tarefa em um projeto (respeita RLS do usu\xE1rio autenticado).",
  inputSchema: {
    project_id: z4.string().uuid().describe("ID do projeto."),
    title: z4.string().min(1).max(200),
    description: z4.string().optional(),
    status: z4.enum(["backlog", "todo", "doing", "review", "done"]).optional(),
    priority: z4.enum(["low", "medium", "high", "urgent"]).optional(),
    due_date: z4.string().optional().describe("ISO date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const status = normalizeTaskStatus(input.status);
    const { data, error } = await sb.from("tasks").insert({
      project_id: input.project_id,
      title: input.title,
      description: input.description ?? null,
      status,
      kanban_status: status,
      priority: input.priority ?? "medium",
      due_date: input.due_date ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Tarefa criada: ${data.id}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/list-contracts.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_contracts_default = defineTool6({
  name: "list_contracts",
  title: "Listar contratos",
  description: "Lista contratos vis\xEDveis ao usu\xE1rio autenticado (RLS aplicado).",
  inputSchema: {
    client_id: z5.string().uuid().optional(),
    status: z5.string().optional(),
    limit: z5.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, status, limit }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    let q = sb.from("contracts").select("id, title, description, status, client_id, project_id, sent_at, admin_signed_at, client_signed_at, created_at, updated_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (client_id) q = q.eq("client_id", client_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} contratos.` }],
      structuredContent: { contracts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gicbrgagstyvbaaumprj";
var mcp_default = defineMcp({
  name: "aceleriq-os",
  title: "Aceleriq OS",
  version: "1.0.0",
  instructions: "Servidor MCP oficial do Aceleriq Performance OS. Ferramentas de leitura e escrita operam como o usu\xE1rio autenticado (RLS aplicado). Use `health` para verificar conectividade, `list_clients`/`list_projects`/`list_tasks`/`list_contracts` para contexto e `create_task` para inserir trabalho no Kanban.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    health_default,
    list_clients_default,
    list_projects_default,
    list_tasks_default,
    list_contracts_default,
    create_task_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
