-- ═══════════════════════════════════════════════════════════════════════
-- MESA ADS: biblioteca da agência (docs/mesa-ads/SPEC.md).
-- Semeia ads_referencias com as 39 fontes do catálogo da pesquisa de
-- 23/09/2026 (docs/mesa-ads/pesquisa/catalogo-referencias.json), como
-- biblioteca da agência: client_id NULL, origem 'catalogo', evidência E0
-- (referência para estudar mecanismo; nenhuma fonte externa prova retorno).
-- ficha guarda aplicação, limite, categoria, status da verificação e o id do
-- catálogo; tags pela categoria.
-- Idempotente: não há chave única por url, então cada linha só entra se a
-- mesma url ainda não existe na biblioteca da agência. Rodar de novo não faz mal.
-- ═══════════════════════════════════════════════════════════════════════

INSERT INTO public.ads_referencias (client_id, titulo, url, origem, evidencia, mecanismo, ficha, tags, destaque, ativa)
SELECT NULL, v.titulo, v.url, 'catalogo', 'E0', v.mecanismo, v.ficha, v.tags, false, true
FROM (VALUES
  ('Natália Torres - perfil', 'https://www.instagram.com/torresnatalia/', NULL, '{"id_catalogo": "N01", "categoria": "perfil", "aplicacao": null, "limite": "Histórico integral não catalogado", "status_verificacao": "Bio lida no Chrome", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['perfil']::text[]),
  ('Ads Rocket - perfil', 'https://www.instagram.com/agenciaadsrocket/', NULL, '{"id_catalogo": "N02", "categoria": "perfil", "aplicacao": null, "limite": "61 posts exibidos; cobertura parcial", "status_verificacao": "Bio e links de feed lidos no Chrome", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['perfil']::text[]),
  ('Black Box Ads', 'https://blackboxads.com.br/', NULL, '{"id_catalogo": "N03", "categoria": "acervo comercial", "aplicacao": "Referências por nicho", "limite": "Conteúdo pago não acessado; validação alegada pelo vendedor", "status_verificacao": "Página comercial lida", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['acervo comercial']::text[]),
  ('Vantablack Ads', 'https://vantablackads.com/', NULL, '{"id_catalogo": "N04", "categoria": "treinamento", "aplicacao": null, "limite": "Aulas não acessadas", "status_verificacao": "Página pública lida e vínculo na bio confirmado", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['treinamento']::text[]),
  ('Método TAP 2.0', 'https://metodotap.com/oficial/', NULL, '{"id_catalogo": "N05", "categoria": "treinamento", "aplicacao": null, "limite": "Aulas não acessadas", "status_verificacao": "Página pública lida", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['treinamento']::text[]),
  ('Ads Rocket - agência', 'https://adsrocket.com.br/', NULL, '{"id_catalogo": "N06", "categoria": "site", "aplicacao": null, "limite": "Resultados comerciais não auditados", "status_verificacao": "Página pública lida e vínculo na bio confirmado", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['site']::text[]),
  ('Kiwicast 154 - processo criativo', 'https://www.youtube.com/watch?v=tbK47vJI6a4&t=1401s', 'situação; contraste; pesquisa', '{"id_catalogo": "N07", "categoria": "entrevista", "aplicacao": "Pesquisa de público e seleção de imagens", "limite": "Não é análise integral do vídeo; legenda automática", "status_verificacao": "Trechos da transcrição automática consultados", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['entrevista']::text[]),
  ('Kiwicast 334', 'https://www.ivoox.com/os-anuncios-que-geraram-milhoes-em-faturamentos-audios-mp3_rf_132882527_1.html', NULL, '{"id_catalogo": "N08", "categoria": "entrevista", "aplicacao": null, "limite": "Não ouvido ou transcrito", "status_verificacao": "Descrição localizada", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['entrevista']::text[]),
  ('EAG 226', 'https://open.spotify.com/episode/0P28PQ1EDUx6dt3fXxm4S4', NULL, '{"id_catalogo": "N09", "categoria": "entrevista", "aplicacao": null, "limite": "Não ouvido ou transcrito", "status_verificacao": "Descrição localizada", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['entrevista']::text[]),
  ('Hackr Ads 03', 'https://open.spotify.com/show/3ui4EdSou8s23M77Z6zhzY', NULL, '{"id_catalogo": "N10", "categoria": "entrevista", "aplicacao": null, "limite": "Link do programa; episódio não ouvido", "status_verificacao": "Programa e descrição localizados", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['entrevista']::text[]),
  ('Contraste emocional', 'https://www.instagram.com/torresnatalia/p/DcvzEx_jmvn/', 'contraste emocional', '{"id_catalogo": "I01", "categoria": "referência E0", "aplicacao": "Humor compatível com a marca", "limite": "Sem métricas de mídia paga", "status_verificacao": "Capa e segundo slide inspecionados visualmente", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['referência e0']::text[]),
  ('Coleção de metáforas', 'https://www.instagram.com/torresnatalia/p/DdRJ0UEjjJ_/', 'metáfora; personificação', '{"id_catalogo": "I02", "categoria": "referência E0", "aplicacao": "Transportar a operação visual", "limite": "Curadoria de terceiros; autoria original não verificada", "status_verificacao": "Capa e segundo slide inspecionados visualmente", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['referência e0']::text[]),
  ('Mensagem centrada no comprador', 'https://www.instagram.com/torresnatalia/p/DcQrMljikLk/', 'comparação', '{"id_catalogo": "I03", "categoria": "referência E0", "aplicacao": "Revisão de argumento", "limite": "Sem prova financeira", "status_verificacao": "Conteúdo acessível e legenda lidos", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['referência e0']::text[]),
  ('Google e Facebook', 'https://www.instagram.com/torresnatalia/p/DdjMd8xDmNu/', 'intenção e descoberta', '{"id_catalogo": "I04", "categoria": "fila de leitura", "aplicacao": null, "limite": "Slides não analisados integralmente; alegações não validadas", "status_verificacao": "Link e tema mapeados no feed", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['fila de leitura']::text[]),
  ('Explicar marketing', 'https://www.instagram.com/torresnatalia/p/DdWXNV4nOhk/', 'metáfora didática', '{"id_catalogo": "I05", "categoria": "fila de leitura", "aplicacao": null, "limite": "Slides não analisados integralmente; alegações não validadas", "status_verificacao": "Link e tema mapeados no feed", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['fila de leitura']::text[]),
  ('Motivos de compra', 'https://www.instagram.com/torresnatalia/p/DdG7XkfjlsY/', 'motivação', '{"id_catalogo": "I06", "categoria": "fila de leitura", "aplicacao": null, "limite": "Slides não analisados integralmente; alegações não validadas", "status_verificacao": "Link e tema mapeados no feed", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['fila de leitura']::text[]),
  ('Coleção de serviços sensíveis', 'https://www.instagram.com/torresnatalia/p/DcleVlDjvew/', 'composição', '{"id_catalogo": "I07", "categoria": "fila de leitura", "aplicacao": null, "limite": "Slides não analisados integralmente; alegações não validadas", "status_verificacao": "Link e tema mapeados no feed", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['fila de leitura']::text[]),
  ('Representação indireta', 'https://www.instagram.com/torresnatalia/p/DciyOERABPE/', 'semiótica', '{"id_catalogo": "I08", "categoria": "fila de leitura", "aplicacao": null, "limite": "Slides não analisados integralmente; alegações não validadas", "status_verificacao": "Link e tema mapeados no feed", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['fila de leitura']::text[]),
  ('Tempo de atendimento', 'https://www.instagram.com/torresnatalia/p/DcJCVhjjmjX/', 'processo comercial', '{"id_catalogo": "I09", "categoria": "fila de leitura", "aplicacao": null, "limite": "Slides não analisados integralmente; alegações não validadas", "status_verificacao": "Link e tema mapeados no feed", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['fila de leitura']::text[]),
  ('Meta Ad Library', 'https://www.facebook.com/ads/library/', NULL, '{"id_catalogo": "B01", "categoria": "biblioteca", "aplicacao": "Anúncios reais e anunciante", "limite": "Não expõe lucro dos concorrentes", "status_verificacao": "Descrição e cobertura públicas verificadas", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['biblioteca']::text[]),
  ('TikTok Top Ads', 'https://ads.tiktok.com/business/creativecenter/inspiration/topads/pc/en', NULL, '{"id_catalogo": "B02", "categoria": "biblioteca", "aplicacao": "Linguagem de vídeo e indicadores públicos", "limite": "Consulta textual sem anúncios retornados; não fornece validação própria", "status_verificacao": "Página e filtros consultados", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['biblioteca']::text[]),
  ('Swiped.co', 'https://swiped.co/', NULL, '{"id_catalogo": "B03", "categoria": "biblioteca", "aplicacao": "Copy e estrutura persuasiva", "limite": "Rótulos de desempenho pertencem ao curador", "status_verificacao": "Índice e exemplo editorial consultados", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['biblioteca']::text[]),
  ('Foreplay Discovery', 'https://www.foreplay.co/discovery', NULL, '{"id_catalogo": "B04", "categoria": "biblioteca comercial", "aplicacao": "Descoberta e organização", "limite": "Não contratado; desempenho não auditado", "status_verificacao": "Página pública consultada", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['biblioteca comercial']::text[]),
  ('Google Ads Transparency', 'https://adstransparency.google.com/', NULL, '{"id_catalogo": "B05", "categoria": "biblioteca", "aplicacao": "Pesquisa complementar de anunciantes", "limite": "Sem busca específica concluída", "status_verificacao": "Página pública aberta", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['biblioteca']::text[]),
  ('Criativos Vantablack - Lucas Emanoel', 'https://www.behance.net/gallery/176246521/Criativos-Vantablack-Natalia-Torres', NULL, '{"id_catalogo": "B06", "categoria": "portfólio E0", "aplicacao": "Direção de arte", "limite": "Todas as pranchas não analisadas", "status_verificacao": "Autoria e existência confirmadas", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['portfólio e0']::text[]),
  ('Natália Torres 2024 - Lucas Emanoel', 'https://www.behance.net/gallery/212089897/Natalia-Torres-2024', NULL, '{"id_catalogo": "B07", "categoria": "portfólio E0", "aplicacao": "Direção de arte", "limite": "Todas as pranchas não analisadas", "status_verificacao": "Autoria e existência confirmadas", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['portfólio e0']::text[]),
  ('TikTok Creative Codes', 'https://ads.tiktok.com/business/en/creative-codes', 'gancho; corpo; fechamento', '{"id_catalogo": "T01", "categoria": "guia oficial", "aplicacao": "Estrutura audiovisual", "limite": "Práticas gerais; não garantia de desempenho", "status_verificacao": "Texto consultado", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['guia oficial']::text[]),
  ('Creative Codes PDF', 'https://ads.tiktok.com/business/library/Creative_Codes_ENG.pdf', NULL, '{"id_catalogo": "T02", "categoria": "PDF oficial", "aplicacao": "Material complementar de estudo", "limite": "Não é ebook da Natália", "status_verificacao": "Localizado na busca oficial", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['pdf oficial']::text[]),
  ('Meta Ad Library API', 'https://es-la.facebook.com/ads/library/api', NULL, '{"id_catalogo": "T03", "categoria": "documentação", "aplicacao": "Avaliar integração futura", "limite": "Cobertura varia por região e categoria", "status_verificacao": "Cobertura pública consultada", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['documentação']::text[]),
  ('coreyhaines31/marketingskills', 'https://github.com/coreyhaines31/marketingskills', NULL, '{"id_catalogo": "G01", "categoria": "GitHub", "aplicacao": "Ver avaliação no dossiê", "limite": "Não instalado nem executado; estrelas não validam criativos", "status_verificacao": "Metadados consultados pela API", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['github']::text[]),
  ('gntrs/swipefile', 'https://github.com/gntrs/swipefile', NULL, '{"id_catalogo": "G02", "categoria": "GitHub", "aplicacao": "Ver avaliação no dossiê", "limite": "Não instalado nem executado; estrelas não validam criativos", "status_verificacao": "Metadados consultados pela API", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['github']::text[]),
  ('proxy-intell/facebook-ads-library-mcp', 'https://github.com/proxy-intell/facebook-ads-library-mcp', NULL, '{"id_catalogo": "G03", "categoria": "GitHub", "aplicacao": "Ver avaliação no dossiê", "limite": "Não instalado nem executado; estrelas não validam criativos", "status_verificacao": "Metadados consultados pela API", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['github']::text[]),
  ('RamsesAguirre777/facebook-ads-library-mcp', 'https://github.com/RamsesAguirre777/facebook-ads-library-mcp', NULL, '{"id_catalogo": "G04", "categoria": "GitHub", "aplicacao": "Ver avaliação no dossiê", "limite": "Não instalado nem executado; estrelas não validam criativos", "status_verificacao": "Metadados consultados pela API", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['github']::text[]),
  ('nord342/ad-whisperer', 'https://github.com/nord342/ad-whisperer', NULL, '{"id_catalogo": "G05", "categoria": "GitHub", "aplicacao": "Ver avaliação no dossiê", "limite": "Não instalado nem executado; estrelas não validam criativos", "status_verificacao": "Metadados consultados pela API", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['github']::text[]),
  ('charlesdove977/advertising-ops', 'https://github.com/charlesdove977/advertising-ops', NULL, '{"id_catalogo": "G06", "categoria": "GitHub", "aplicacao": "Ver avaliação no dossiê", "limite": "Não instalado nem executado; estrelas não validam criativos", "status_verificacao": "Metadados consultados pela API", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['github']::text[]),
  ('nothingbutcici/product-swipefile', 'https://github.com/nothingbutcici/product-swipefile', NULL, '{"id_catalogo": "G07", "categoria": "GitHub", "aplicacao": "Ver avaliação no dossiê", "limite": "Não instalado nem executado; estrelas não validam criativos", "status_verificacao": "Metadados consultados pela API", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['github']::text[]),
  ('no-chili/awesome-gpt-image-2-prompts', 'https://github.com/no-chili/awesome-gpt-image-2-prompts', NULL, '{"id_catalogo": "G08", "categoria": "GitHub", "aplicacao": "Ver avaliação no dossiê", "limite": "Não instalado nem executado; estrelas não validam criativos", "status_verificacao": "Metadados consultados pela API", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['github']::text[]),
  ('cenoura/awesome-ads', 'https://github.com/cenoura/awesome-ads', NULL, '{"id_catalogo": "G09", "categoria": "GitHub", "aplicacao": "Ver avaliação no dossiê", "limite": "Não instalado nem executado; estrelas não validam criativos", "status_verificacao": "Metadados consultados pela API", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['github']::text[]),
  ('minimaxir/facebook-ad-library-scraper', 'https://github.com/minimaxir/facebook-ad-library-scraper', NULL, '{"id_catalogo": "G10", "categoria": "GitHub", "aplicacao": "Ver avaliação no dossiê", "limite": "Não instalado nem executado; estrelas não validam criativos", "status_verificacao": "Metadados consultados pela API", "data_coleta": "2026-09-23", "fonte": "docs/mesa-ads/pesquisa/catalogo-referencias.json"}'::jsonb, ARRAY['github']::text[])
) AS v (titulo, url, mecanismo, ficha, tags)
WHERE NOT EXISTS (
  SELECT 1 FROM public.ads_referencias r
  WHERE r.client_id IS NULL AND r.url = v.url
);
